const premiumProducts = [
  { id: 101, category: "Music", title: "Apple Music", slug: "apple-music", priceText: "ARS 2.000", badge: "En stock", image: "./img/products/applemusic.webp", link: "#", description: "Apple Music 1 Mes - Música Sin Límites con 33Store.\nDisfrutá del catálogo oficial de Apple Music con más de 100 millones de canciones en Audio Espacial y Lossless sin interrupciones.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Calidad Lossless & Dolby Atmos: Audio de máxima fidelidad para audiófilos.\n  Sin Anuncios: Escuchá tus listas y artistas favoritos sin cortes.\n  Descargas Offline: Guardá álbumes enteros para escuchar sin conexión a internet.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te enviamos la invitación o código oficial apenas se procesa el pago.\n  100% Legal & Seguro: Respaldado por la garantía de 33Store.\n\nSOPORTE\n  Soporte 24/7 de 33Store para asistirte con la activación en tus dispositivos iOS, Android o PC." },
  { 
    id: 102, category: "Creator Tools", title: "Canva Premium", slug: "canva-premium", priceText: "ARS 1.287 - ARS 5.733", badge: "2 products", image: "./img/products/canva.webp", link: "#",
    subProducts: [
      { id: 1021, title: "Canva Premium [1 month]", slug: "canva-premium-1-month", priceText: "ARS 1.287", badge: "En stock", image: "./img/products/canva.webp", description: "Canva Premium - Diseñá como un Profesional con 33Store.\nLlevá tus diseños al siguiente nivel con acceso a todas las herramientas premium, plantillas exclusivas y elementos pro de Canva.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Herramientas Pro: Removedor de fondos, redimensionamiento mágico y organizador de marca.\n  En Tu Propia Cuenta: La mejora se aplica directamente a tu correo electrónico personal de Canva mediante un enlace de invitación.\n  Sin Marca de Agua: Exportá todos tus trabajos en máxima calidad y sin limitaciones.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te enviamos la invitación a tu email al instante.\n  Garantía Lifetime (Auto Replace): Para los planes Lifetime, 33Store asegura una reposición inmediata en caso de perder el acceso al equipo pro.\n\nSOPORTE\n  Asistencia garantizada para que nunca te quedes a mitad de un diseño. Contactanos vía Discord o Web." },
      { id: 1022, title: "Canva Premium Keys Lifetime [Your Own Account]", slug: "canva-premium-keys-lifetime-your-own-account", priceText: "ARS 5.733", badge: "En stock", image: "./img/products/canva.webp", description: "Canva Premium - Diseñá como un Profesional con 33Store.\nLlevá tus diseños al siguiente nivel con acceso a todas las herramientas premium, plantillas exclusivas y elementos pro de Canva.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Herramientas Pro: Removedor de fondos, redimensionamiento mágico y organizador de marca.\n  En Tu Propia Cuenta: La mejora se aplica directamente a tu correo electrónico personal de Canva mediante un enlace de invitación.\n  Sin Marca de Agua: Exportá todos tus trabajos en máxima calidad y sin limitaciones.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te enviamos la invitación a tu email al instante.\n  Garantía Lifetime (Auto Replace): Para los planes Lifetime, 33Store asegura una reposición inmediata en caso de perder el acceso al equipo pro.\n\nSOPORTE\n  Asistencia garantizada para que nunca te quedes a mitad de un diseño. Contactanos vía Discord o Web." }
    ]
  },
  { id: 103, category: "Creator Tools", title: "CapCut Pro", slug: "capcut-pro", priceText: "ARS 1.500", badge: "En stock", image: "./img/products/capcut.webp", link: "#", description: "CapCut Pro Lifetime - Edición de Video Profesional con 33Store.\nDesbloqueá todas las funciones premium, efectos pro, transiciones exclusivas y herramientas de IA en CapCut.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Funciones Pro Liberadas: Subtítulos automáticos, removido de fondo con IA, filtros exclusivos y exportación 4K 60fps.\n  Herramientas de IA: Generación de efectos de voz y retoque facial avanzado.\n  Sin Marca de Agua: Exportá proyectos limpios y listos para TikTok, Reels o YouTube.\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales o método de activación entregado al instante.\n  Acceso: Acceso total vía navegador web (algunas cuentas pueden no ser compatibles con la aplicación).\n  Garantía 33Store: Reposición inmediata ante cualquier inconveniente.\n\nSOPORTE\n  Asistencia técnica y ayuda paso a paso desde el equipo de 33Store." },
  { 
    id: 104, category: "AI Tools", title: "ChatGPT", slug: "chatgpt", priceText: "ARS 2.223 - ARS 15.093", badge: "3 products", image: "./img/products/chatgpt.webp", link: "#",
    subProducts: [
      { id: 1041, title: "ChatGPT Unlimited [1 Day]", slug: "chatgpt-unlimited-1-day", priceText: "ARS 2.223", badge: "En stock", image: "./img/products/chatgpt.webp", description: "ChatGPT Plus / Unlimited - Respuestas Rápidas sin Límites con 33Store.\nAccedé a GPT-4 y las herramientas avanzadas de OpenAI sin restricciones molestos.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Sin Límites Prácticos: Olvidate del mensaje de limitación constante.\n  Herramientas Plus: Acceso a DALL-E 3, análisis de datos avanzado y navegación web.\n  Confiabilidad 33Store: Accesos premium configurados para alta disponibilidad.\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Recibís los datos de acceso al instante tras tu compra.\n  Privacidad: Acceso seguro mediante nuestro sistema verificado.\n\nSOPORTE\n  Reemplazo inmediato garantizado ante cualquier fallo temporal gracias a la política de 33Store." },
      { id: 1042, title: "ChatGPT Unlimited [7 Days]", slug: "chatgpt-unlimited-7-days", priceText: "ARS 6.435", badge: "En stock", image: "./img/products/chatgpt.webp", description: "ChatGPT Plus / Unlimited - Respuestas Rápidas sin Límites con 33Store.\nAccedé a GPT-4 y las herramientas avanzadas de OpenAI sin restricciones molestos.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Sin Límites Prácticos: Olvidate del mensaje de limitación constante.\n  Herramientas Plus: Acceso a DALL-E 3, análisis de datos avanzado y navegación web.\n  Confiabilidad 33Store: Accesos premium configurados para alta disponibilidad.\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Recibís los datos de acceso al instante tras tu compra.\n  Privacidad: Acceso seguro mediante nuestro sistema verificado.\n\nSOPORTE\n  Reemplazo inmediato garantizado ante cualquier fallo temporal gracias a la política de 33Store." },
      { id: 1043, title: "ChatGPT Unlimited [30 Days]", slug: "chatgpt-unlimited-30-days", priceText: "ARS 15.093", badge: "En stock", image: "./img/products/chatgpt.webp", description: "ChatGPT Plus / Unlimited - Respuestas Rápidas sin Límites con 33Store.\nAccedé a GPT-4 y las herramientas avanzadas de OpenAI sin restricciones molestos.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Sin Límites Prácticos: Olvidate del mensaje de limitación constante.\n  Herramientas Plus: Acceso a DALL-E 3, análisis de datos avanzado y navegación web.\n  Confiabilidad 33Store: Accesos premium configurados para alta disponibilidad.\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Recibís los datos de acceso al instante tras tu compra.\n  Privacidad: Acceso seguro mediante nuestro sistema verificado.\n\nSOPORTE\n  Reemplazo inmediato garantizado ante cualquier fallo temporal gracias a la política de 33Store." }
    ]
  },
  { id: 105, category: "Gaming", title: "Cheats", slug: "cheats", priceText: "ARS 23.283 - ARS 70.083", badge: "2 products", image: "./img/products/cheats.webp", link: "#",
    subProducts: [
      { id: 1051, title: "Fortnite Cheat", slug: "fortnite-cheat", priceText: "ARS 23.283 - ARS 70.083", badge: "En stock", image: "./img/products/cheats.webp", description: "Cheats Premium & Software - Ventaja Competitiva Segura con 33Store.\nHerramientas de asistencia premium, seguras y actualizadas para los juegos más competitivos del mercado.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Opciones Disponibles: Fortnite, Black Ops / Warzone, y más.\n  Funciones Avanzadas: Aimbot preciso, ESP (Wallhack), Radar y configuraciones personalizables para jugar Legit o Rage.\n  Undetected: Software privado y constantemente actualizado para evitar baneos.\n\nCALIDAD Y ENTREGA\n  Entrega Instantánea: Descargá tu software y key de activación ni bien finaliza tu compra.\n  Fácil Instalación: Instrucciones paso a paso incluidas.\n\nSOPORTE\n  Aviso Importante: El uso de software de terceros siempre conlleva un riesgo. En 33Store te asesoramos sobre configuraciones seguras, pero el uso final es bajo tu propia responsabilidad." },
      { id: 1052, title: "Black Ops 7 & War Zone Cheat", slug: "black-ops-7-war-zone-cheat", priceText: "ARS 23.283 - ARS 70.083", badge: "En stock", image: "./img/products/cheats.webp", description: "Cheats Premium & Software - Ventaja Competitiva Segura con 33Store.\nHerramientas de asistencia premium, seguras y actualizadas para los juegos más competitivos del mercado.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Opciones Disponibles: Fortnite, Black Ops / Warzone, y más.\n  Funciones Avanzadas: Aimbot preciso, ESP (Wallhack), Radar y configuraciones personalizables para jugar Legit o Rage.\n  Undetected: Software privado y constantemente actualizado para evitar baneos.\n\nCALIDAD Y ENTREGA\n  Entrega Instantánea: Descargá tu software y key de activación ni bien finaliza tu compra.\n  Fácil Instalación: Instrucciones paso a paso incluidas.\n\nSOPORTE\n  Aviso Importante: El uso de software de terceros siempre conlleva un riesgo. En 33Store te asesoramos sobre configuraciones seguras, pero el uso final es bajo tu propia responsabilidad." }
    ]
  },
  { 
    id: 106, category: "AI Tools", title: "Claude Unlimited", slug: "claude-unlimited", priceText: "ARS 5.359 - ARS 326.313", badge: "5 products", image: "./img/products/claude.webp", link: "#",
    subProducts: [
      { id: 1061, title: "Claude Unlimited [1 Day]", slug: "claude-unlimited-1-day", priceText: "ARS 5.359", badge: "En stock", image: "./img/products/claude.webp", description: "Claude Pro Unlimited - IA Avanzada Sin Límites gracias a 33Store.\nAccedé a toda la potencia del modelo Claude (Anthropic) sin restricciones de uso y con entrega inmediata.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Acceso Pro: Respuestas más rápidas, ventanas de contexto enormes y cero límites molestos.\n  Suscripción Asegurada: Tu cuenta funcionará ininterrumpidamente durante todo el período contratado.\n  Garantía 33Store: Renuevos y reemplazos inmediatos si surge cualquier inconveniente.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te entregamos las credenciales de acceso apenas se procesa el pago.\n  Privacidad Total: Tu entorno es seguro y cuenta con el respaldo de 33Store.\n\nSOPORTE\n  Soporte prioritario 24/7. Nuestro equipo de 33Store te asiste ante cualquier caída de plataforma." },
      { id: 1062, title: "Claude Unlimited [7 Days]", slug: "claude-unlimited-7-days", priceText: "ARS 17.527", badge: "En stock", image: "./img/products/claude.webp", description: "Claude Pro Unlimited - IA Avanzada Sin Límites gracias a 33Store.\nAccedé a toda la potencia del modelo Claude (Anthropic) sin restricciones de uso y con entrega inmediata.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Acceso Pro: Respuestas más rápidas, ventanas de contexto enormes y cero límites molestos.\n  Suscripción Asegurada: Tu cuenta funcionará ininterrumpidamente durante todo el período contratado.\n  Garantía 33Store: Renuevos y reemplazos inmediatos si surge cualquier inconveniente.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te entregamos las credenciales de acceso apenas se procesa el pago.\n  Privacidad Total: Tu entorno es seguro y cuenta con el respaldo de 33Store.\n\nSOPORTE\n  Soporte prioritario 24/7. Nuestro equipo de 33Store te asiste ante cualquier caída de plataforma." },
      { id: 1063, title: "Claude Unlimited [30 Days]", slug: "claude-unlimited-30-days", priceText: "ARS 39.663", badge: "En stock", image: "./img/products/claude.webp", description: "Claude Pro Unlimited - IA Avanzada Sin Límites gracias a 33Store.\nAccedé a toda la potencia del modelo Claude (Anthropic) sin restricciones de uso y con entrega inmediata.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Acceso Pro: Respuestas más rápidas, ventanas de contexto enormes y cero límites molestos.\n  Suscripción Asegurada: Tu cuenta funcionará ininterrumpidamente durante todo el período contratado.\n  Garantía 33Store: Renuevos y reemplazos inmediatos si surge cualquier inconveniente.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te entregamos las credenciales de acceso apenas se procesa el pago.\n  Privacidad Total: Tu entorno es seguro y cuenta con el respaldo de 33Store.\n\nSOPORTE\n  Soporte prioritario 24/7. Nuestro equipo de 33Store te asiste ante cualquier caída de plataforma." },
      { id: 1064, title: "Claude Unlimited [6 Months]", slug: "claude-unlimited-6-months", priceText: "ARS 175.383", badge: "En stock", image: "./img/products/claude.webp", description: "Claude Pro Unlimited - IA Avanzada Sin Límites gracias a 33Store.\nAccedé a toda la potencia del modelo Claude (Anthropic) sin restricciones de uso y con entrega inmediata.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Acceso Pro: Respuestas más rápidas, ventanas de contexto enormes y cero límites molestos.\n  Suscripción Asegurada: Tu cuenta funcionará ininterrumpidamente durante todo el período contratado.\n  Garantía 33Store: Renuevos y reemplazos inmediatos si surge cualquier inconveniente.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te entregamos las credenciales de acceso apenas se procesa el pago.\n  Privacidad Total: Tu entorno es seguro y cuenta con el respaldo de 33Store.\n\nSOPORTE\n  Soporte prioritario 24/7. Nuestro equipo de 33Store te asiste ante cualquier caída de plataforma." },
      { id: 1065, title: "Claude Unlimited [1 Year]", slug: "claude-unlimited-1-year", priceText: "ARS 326.313", badge: "En stock", image: "./img/products/claude.webp", description: "Claude Pro Unlimited - IA Avanzada Sin Límites gracias a 33Store.\nAccedé a toda la potencia del modelo Claude (Anthropic) sin restricciones de uso y con entrega inmediata.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Acceso Pro: Respuestas más rápidas, ventanas de contexto enormes y cero límites molestos.\n  Suscripción Asegurada: Tu cuenta funcionará ininterrumpidamente durante todo el período contratado.\n  Garantía 33Store: Renuevos y reemplazos inmediatos si surge cualquier inconveniente.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Te entregamos las credenciales de acceso apenas se procesa el pago.\n  Privacidad Total: Tu entorno es seguro y cuenta con el respaldo de 33Store.\n\nSOPORTE\n  Soporte prioritario 24/7. Nuestro equipo de 33Store te asiste ante cualquier caída de plataforma." }
    ]
  },
  { 
    id: 107, category: "Streaming", title: "Crunchyroll", slug: "crunchyroll", priceText: "ARS 1.000 - ARS 1.521", badge: "2 products", image: "./img/products/crunchyroll.webp", link: "#",
    subProducts: [
      { id: 1071, title: "Crunchyroll Lifetime [FAN]", slug: "crunchyroll-lifetime-fan", priceText: "ARS 1.000", badge: "En stock", image: "./img/products/crunchyroll.webp", description: "Crunchyroll Premium Lifetime - El Mejor Anime de por Vida con 33Store.\nMirá tus animes favoritos el mismo día de su estreno en Japón, en Full HD y sin publicidad.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Una suscripción definitiva sin pagar mes a mes.\n  Planes Fan & Mega Fan: Elegí el plan Mega Fan (Keys Auto Replace) para aplicarlo directamente a tu propia cuenta y tener descargas offline.\n  Catálogo Completo: Todo el anime subtitulado y doblado, con lanzamientos simultáneos (Simulcast).\n\nCALIDAD Y ENTREGA\n  Garantía 33Store: Nuestro sistema asegura que siempre tengas acceso mediante reposiciones si fuesen necesarias.\n  Entrega Rápida: Recibís tu acceso al instante tras la compra.\n\nSOPORTE\n  Soporte especializado 24/7 mediante nuestro servidor de Discord o tickets directos." },
      { id: 1072, title: "Crunchyroll Lifetime Mega Fan Keys [Auto Replace]", slug: "crunchyroll-lifetime-mega-fan-keys-auto-replace", priceText: "ARS 1.521", badge: "En stock", image: "./img/products/crunchyroll.webp", description: "Crunchyroll Premium Lifetime - El Mejor Anime de por Vida con 33Store.\nMirá tus animes favoritos el mismo día de su estreno en Japón, en Full HD y sin publicidad.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Una suscripción definitiva sin pagar mes a mes.\n  Planes Fan & Mega Fan: Elegí el plan Mega Fan (Keys Auto Replace) para aplicarlo directamente a tu propia cuenta y tener descargas offline.\n  Catálogo Completo: Todo el anime subtitulado y doblado, con lanzamientos simultáneos (Simulcast).\n\nCALIDAD Y ENTREGA\n  Garantía 33Store: Nuestro sistema asegura que siempre tengas acceso mediante reposiciones si fuesen necesarias.\n  Entrega Rápida: Recibís tu acceso al instante tras la compra.\n\nSOPORTE\n  Soporte especializado 24/7 mediante nuestro servidor de Discord o tickets directos." }
    ]
  },
  { 
    id: 108, category: "Sports Streaming", title: "DAZN Lifetime", slug: "dazn-lifetime", priceText: "ARS 592 - ARS 4.141", badge: "5 products", image: "./img/products/daznlife.webp", link: "#",
    subProducts: [
      { id: 1081, title: "Dazn Lifetime [ Random Sub ]", slug: "dazn-lifetime-random-sub", priceText: "ARS 1.053", badge: "En stock", image: "./img/products/daznlife.webp", description: "DAZN Lifetime - La Casa del Deporte en Vivo con 33Store.\nAccedé a la plataforma de streaming deportivo más grande del mundo, incluyendo fútbol, motor, boxeo y más, con un solo pago.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Olvidate de las cuotas mensuales. Pagás una vez y mirás siempre.\n  Opciones Regionales (ESP): Elegí tu paquete favorito (Motor, Fútbol o Total) para disfrutar del contenido de España.\n  Garantía Lifetime 33Store: Con nuestro sistema de reposición, asegurás tu inversión a largo plazo.\n\nCALIDAD Y ENTREGA\n  Transmisión en Alta Calidad: Partidos y carreras en HD sin retrasos.\n  Entrega Instantánea: Recibís usuario y contraseña apenas el sistema procesa tu orden.\n\nSOPORTE\n  Asistencia técnica 24/7. Nuestro equipo de 33Store está siempre listo para ayudarte con configuraciones de región o reposiciones." },
      { id: 1082, title: "Dazn Lifetime ESP [ Random Sub ]", slug: "dazn-lifetime-esp-random-sub", priceText: "ARS 819", badge: "En stock", image: "./img/products/daznlife.webp", description: "DAZN Lifetime - La Casa del Deporte en Vivo con 33Store.\nAccedé a la plataforma de streaming deportivo más grande del mundo, incluyendo fútbol, motor, boxeo y más, con un solo pago.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Olvidate de las cuotas mensuales. Pagás una vez y mirás siempre.\n  Opciones Regionales (ESP): Elegí tu paquete favorito (Motor, Fútbol o Total) para disfrutar del contenido de España.\n  Garantía Lifetime 33Store: Con nuestro sistema de reposición, asegurás tu inversión a largo plazo.\n\nCALIDAD Y ENTREGA\n  Transmisión en Alta Calidad: Partidos y carreras en HD sin retrasos.\n  Entrega Instantánea: Recibís usuario y contraseña apenas el sistema procesa tu orden.\n\nSOPORTE\n  Asistencia técnica 24/7. Nuestro equipo de 33Store está siempre listo para ayudarte con configuraciones de región o reposiciones." },
      { id: 1083, title: "Dazn Lifetime ESP [ Motor ]", slug: "dazn-lifetime-esp-motor", priceText: "ARS 1.404", badge: "En stock", image: "./img/products/daznlife.webp", description: "DAZN Lifetime - La Casa del Deporte en Vivo con 33Store.\nAccedé a la plataforma de streaming deportivo más grande del mundo, incluyendo fútbol, motor, boxeo y más, con un solo pago.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Olvidate de las cuotas mensuales. Pagás una vez y mirás siempre.\n  Opciones Regionales (ESP): Elegí tu paquete favorito (Motor, Fútbol o Total) para disfrutar del contenido de España.\n  Garantía Lifetime 33Store: Con nuestro sistema de reposición, asegurás tu inversión a largo plazo.\n\nCALIDAD Y ENTREGA\n  Transmisión en Alta Calidad: Partidos y carreras en HD sin retrasos.\n  Entrega Instantánea: Recibís usuario y contraseña apenas el sistema procesa tu orden.\n\nSOPORTE\n  Asistencia técnica 24/7. Nuestro equipo de 33Store está siempre listo para ayudarte con configuraciones de región o reposiciones." },
      { id: 1084, title: "Dazn Lifetime ESP [ Futbol ]", slug: "dazn-lifetime-esp-futbol", priceText: "ARS 1.638", badge: "En stock", image: "./img/products/daznlife.webp", description: "DAZN Lifetime - La Casa del Deporte en Vivo con 33Store.\nAccedé a la plataforma de streaming deportivo más grande del mundo, incluyendo fútbol, motor, boxeo y más, con un solo pago.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Olvidate de las cuotas mensuales. Pagás una vez y mirás siempre.\n  Opciones Regionales (ESP): Elegí tu paquete favorito (Motor, Fútbol o Total) para disfrutar del contenido de España.\n  Garantía Lifetime 33Store: Con nuestro sistema de reposición, asegurás tu inversión a largo plazo.\n\nCALIDAD Y ENTREGA\n  Transmisión en Alta Calidad: Partidos y carreras en HD sin retrasos.\n  Entrega Instantánea: Recibís usuario y contraseña apenas el sistema procesa tu orden.\n\nSOPORTE\n  Asistencia técnica 24/7. Nuestro equipo de 33Store está siempre listo para ayudarte con configuraciones de región o reposiciones." },
      { id: 1085, title: "Dazn Lifetime ESP [ Total ]", slug: "dazn-lifetime-esp-total", priceText: "ARS 5.733", badge: "En stock", image: "./img/products/daznlife.webp", description: "DAZN Lifetime - La Casa del Deporte en Vivo con 33Store.\nAccedé a la plataforma de streaming deportivo más grande del mundo, incluyendo fútbol, motor, boxeo y más, con un solo pago.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único (Lifetime): Olvidate de las cuotas mensuales. Pagás una vez y mirás siempre.\n  Opciones Regionales (ESP): Elegí tu paquete favorito (Motor, Fútbol o Total) para disfrutar del contenido de España.\n  Garantía Lifetime 33Store: Con nuestro sistema de reposición, asegurás tu inversión a largo plazo.\n\nCALIDAD Y ENTREGA\n  Transmisión en Alta Calidad: Partidos y carreras en HD sin retrasos.\n  Entrega Instantánea: Recibís usuario y contraseña apenas el sistema procesa tu orden.\n\nSOPORTE\n  Asistencia técnica 24/7. Nuestro equipo de 33Store está siempre listo para ayudarte con configuraciones de región o reposiciones." }
    ]
  },
  { 
    id: 109, category: "Discord", title: "Discord Services", slug: "discord-services", priceText: "ARS 2.083 - ARS 54.405", badge: "3 products", image: "./img/products/discord.webp", link: "#",
    subProducts: [
      { id: 1091, title: "Discord Real Server Members [KEYS]", slug: "discord-real-server-members-keys", priceText: "ARS 4.563 - ARS 40.804", badge: "En stock", image: "./img/products/discord/discmembers.webp", description: "Real Discord Members - Sistema por Keys exclusivo de 33Store.\nServicio de alta calidad que provee miembros 100% reales y activos para tu servidor a través del sistema de keys más seguro del mercado.\n\nCARACTERÍSTICAS DEL SERVICIO\n  100% Miembros Reales: Solo usuarios genuinos. Cero bots, cero riesgo.\n  Garantía 33Store: Recibís exactamente la cantidad comprada, respaldada por nuestro equipo.\n  Entrega Inmediata: Procesamiento ultra rápido sin poner en riesgo tu servidor.\n\nCALIDAD Y ENTREGA\n  Sistema Avanzado de Keys: Los miembros se reclaman cuando vos quieras mediante llaves privadas.\n  Sin Vencimiento: Las keys nunca expiran, tu saldo queda guardado para siempre.\n  Marca Blanca: Ideal para revendedores. Entregá a tus clientes sin que vean nuestra marca.\n\nSOPORTE\n  Soporte 24/7 en español mediante nuestro canal oficial de Discord o tickets directos en 33Store.", variants: [
        {"name":"500 MEMBERS","priceText":"ARS 4.563","desc":"Entrega Inmediata", "minQty": 1, "priceNum": 4563},
        {"name":"1000 MEMBERS","priceText":"ARS 8.073","desc":"Entrega Inmediata", "minQty": 1, "priceNum": 8073},
        {"name":"2000 MEMBERS","priceText":"ARS 11.320","desc":"Entrega Inmediata", "minQty": 1, "priceNum": 11320, "originalPriceText":"ARS 15.093", "originalPriceNum": 15093, "discountBadge":"-25%"},
        {"name":"3000 MEMBERS","priceText":"ARS 16.585","desc":"Entrega Inmediata", "minQty": 1, "priceNum": 16585, "originalPriceText":"ARS 22.113", "originalPriceNum": 22113, "discountBadge":"-25%"},
        {"name":"4000 MEMBERS","priceText":"ARS 20.972","desc":"Entrega Inmediata", "minQty": 1, "priceNum": 20972, "originalPriceText":"ARS 27.963", "originalPriceNum": 27963, "discountBadge":"-25%"},
        {"name":"5000 MEMBERS","priceText":"ARS 25.360","desc":"Entrega Inmediata", "minQty": 1, "priceNum": 25360, "originalPriceText":"ARS 33.813", "originalPriceNum": 33813, "discountBadge":"-25%"},
        {"name":"6000 MEMBERS","priceText":"ARS 27.466","desc":"Agotado temporalmente", "minQty": 1, "priceNum": 27466, "originalPriceText":"ARS 36.621", "originalPriceNum": 36621, "discountBadge":"-25%"},
        {"name":"7000 MEMBERS","priceText":"ARS 32.029","desc":"Agotado temporalmente", "minQty": 1, "priceNum": 32029, "originalPriceText":"ARS 42.705", "originalPriceNum": 42705, "discountBadge":"-25%"},
        {"name":"8000 MEMBERS","priceText":"ARS 36.241","desc":"Agotado temporalmente", "minQty": 1, "priceNum": 36241, "originalPriceText":"ARS 48.321", "originalPriceNum": 48321, "discountBadge":"-25%"},
        {"name":"9000 MEMBERS","priceText":"ARS 40.804","desc":"Agotado temporalmente", "minQty": 1, "priceNum": 40804, "originalPriceText":"ARS 54.405", "originalPriceNum": 54405, "discountBadge":"-25%"}
      ] },
      { id: 1092, title: "Nitro Promocode [3 Months]", slug: "nitro-promocode-3-months", priceText: "ARS 2.083", badge: "En stock", image: "./img/products/discord/nitropromocode.webp", description: "Discord Nitro Promocode (3 Meses) - Activación Inmediata con 33Store.\nDisfrutá de todos los beneficios premium de Discord por 3 meses enteros con nuestro sistema automatizado.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Nitro Full: 2 Mejoras de servidor (Boosts), avatares animados, emojis globales y streaming en HD.\n  Activación Rápida: Recibís un código promocional oficial listo para canjear en tu cuenta.\n  Calidad 33Store: Garantizamos la validez y origen lícito de todos nuestros códigos.\n\nCALIDAD Y ENTREGA\n  Requisitos: Tu cuenta no debe haber tenido Nitro activo en los últimos 12 meses. Requiere método de pago para activar (no te cobran).\n  Entrega Instantánea: Recibís tu link apenas confirmás el pago en 33Store.\n\nSOPORTE\n  Garantía y ayuda paso a paso desde nuestro centro de soporte." },
      { id: 1093, title: "Nitro Tokens", slug: "nitro-tokens", priceText: "ARS 2.925", badge: "En stock", image: "./img/products/discord/nitrotoken.webp", description: "Discord Nitro Tokens - Sistema Avanzado para Desarrolladores y Servidores.\nTokens de Discord Nitro de alta calidad y verificados, listos para integraciones y herramientas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Tokens 100% Verificados: Cuentas estables para uso profesional con Nitro activo.\n  Entrega Segura: Sistema automatizado que entrega directamente el token sin intermediarios.\n\nCALIDAD Y ENTREGA\n  Durabilidad 33Store: Probados rigurosamente para garantizar su tiempo de vida útil.\n  Formato Limpio: Formato estándar compatible con la mayoría de herramientas del mercado.\n\nSOPORTE\n  Soporte especializado de 33Store para garantizar que el token entregado funciona al 100%.", variants: [
        { name: "Nitro Token [1 Mes]", priceText: "ARS 2.925", desc: "Entrega Inmediata", minQty: 1, priceNum: 2925 },
        { name: "Nitro Token [3 Meses]", priceText: "ARS 4.680", desc: "Entrega Inmediata", minQty: 1, priceNum: 4680 }
      ] }
    ]
  },
  { 
    id: 110, category: "Streaming", title: "Disney+ Lifetime", slug: "disney-lifetime", priceText: "ARS 337 - ARS 1.544", badge: "3 products", image: "./img/products/disney+.webp", link: "#",
    subProducts: [
      { id: 1101, title: "Disney+ [Only Disney+]", slug: "disney-only-disney", priceText: "ARS 337", badge: "En stock", image: "./img/products/disney+.webp", description: "Disney+ / Hulu / ESPN+ - Todo el Entretenimiento y Deporte con 33Store.\nDisfrutá del mundo mágico de Disney, las series de Hulu y los deportes de ESPN en un solo lugar.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Opciones a Medida: Elegí el combo que mejor se adapte a vos (Solo Disney+, con Hulu o el bundle completo con ESPN+).\n  Máxima Resolución: Reproducción en 4K UHD para aprovechar tu Smart TV al máximo.\n  Cuentas Seguras: Acceso premium garantizado y administrado por 33Store.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Recibís las credenciales apenas se aprueba tu pago.\n  Perfiles Premium: Disfrutá sin cortes, sin publicidades y con el catálogo completamente liberado.\n\nSOPORTE\n  Cobertura total. Ante cualquier inconveniente, nuestro equipo de soporte te lo resuelve en minutos." },
      { id: 1102, title: "Disney+ [DISNEY+ & HULU]", slug: "disney-disney-hulu", priceText: "ARS 702", badge: "En stock", image: "./img/products/disney+.webp", description: "Disney+ / Hulu / ESPN+ - Todo el Entretenimiento y Deporte con 33Store.\nDisfrutá del mundo mágico de Disney, las series de Hulu y los deportes de ESPN en un solo lugar.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Opciones a Medida: Elegí el combo que mejor se adapte a vos (Solo Disney+, con Hulu o el bundle completo con ESPN+).\n  Máxima Resolución: Reproducción en 4K UHD para aprovechar tu Smart TV al máximo.\n  Cuentas Seguras: Acceso premium garantizado y administrado por 33Store.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Recibís las credenciales apenas se aprueba tu pago.\n  Perfiles Premium: Disfrutá sin cortes, sin publicidades y con el catálogo completamente liberado.\n\nSOPORTE\n  Cobertura total. Ante cualquier inconveniente, nuestro equipo de soporte te lo resuelve en minutos." },
      { id: 1103, title: "Disney+ [DISNEY+ & HULU & ESPN+]", slug: "disney-disney-hulu-espn", priceText: "ARS 1.544", badge: "En stock", image: "./img/products/disney+.webp", description: "Disney+ / Hulu / ESPN+ - Todo el Entretenimiento y Deporte con 33Store.\nDisfrutá del mundo mágico de Disney, las series de Hulu y los deportes de ESPN en un solo lugar.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Opciones a Medida: Elegí el combo que mejor se adapte a vos (Solo Disney+, con Hulu o el bundle completo con ESPN+).\n  Máxima Resolución: Reproducción en 4K UHD para aprovechar tu Smart TV al máximo.\n  Cuentas Seguras: Acceso premium garantizado y administrado por 33Store.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Recibís las credenciales apenas se aprueba tu pago.\n  Perfiles Premium: Disfrutá sin cortes, sin publicidades y con el catálogo completamente liberado.\n\nSOPORTE\n  Cobertura total. Ante cualquier inconveniente, nuestro equipo de soporte te lo resuelve en minutos." }
    ]
  },
  { id: 111, category: "Software & Learning", title: "Duolingo", slug: "duolingo", priceText: "ARS 1.000", badge: "En stock", image: "./img/products/duolingo.webp", link: "#", description: "Duolingo Super Lifetime - Aprendé Idiomas Sin Límites con 33Store.\nAccedé a Duolingo Super de por vida y aprendé idiomas a tu ritmo sin vidas limitadas ni anuncios.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Vidas Ilimitadas: Cometé los errores que necesites para aprender sin esperar horas a recuperar vidas.\n  Sin Publicidad: Cero interrupciones comerciales durante tus lecciones diarias.\n  Repaso de Errores: Lecciones personalizadas enfocadas en corregir tus puntos débiles.\n\nCALIDAD Y ENTREGA\n  En Tu Propia Cuenta: Activación segura vinculada a tu perfil de Duolingo.\n  Pago Único: Olvidate de suscripciones mensuales.\n\nSOPORTE\n  Soporte especializado de 33Store garantizando la permanencia de tu suscripción Super." },
  { id: 112, category: "VPN & Security", title: "ExpressVPN Lifetime", slug: "expressvpn-lifetime", priceText: "ARS 1.000", badge: "En stock", image: "./img/products/expressvpn.webp", link: "#", description: "ExpressVPN Premium Lifetime - Máxima Velocidad y Privacidad con 33Store.\nNavegá de forma 100% anónima, protegé tus datos personales y desbloqueá catálogos globales de streaming con la VPN #1 del mundo.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Servidores Ultra Rápidos: Red global optimizada en más de 90 países con ancho de banda ilimitado.\n  Desbloqueo de Streaming: Accedé a catálogos de Netflix EEUU, Hulu, BBC iPlayer y más sin bloqueos.\n  Encriptación Militar: Encriptación AES-256 bits para proteger tus transacciones y redes Wi-Fi públicas.\n\nCALIDAD Y ENTREGA\n  Multi-Dispositivo: Compatible con Windows, Mac, Android, iOS y Smart TVs.\n  Garantía Lifetime 33Store: Cobertura y reposiciones garantizadas por nuestro equipo.\n\nSOPORTE\n  Atención 24/7 para resolver dudas de conexión o configuración." },
  { 
    id: 113, category: "AI Tools", title: "Gemini", slug: "gemini", priceText: "ARS 9.243 - ARS 11.583", badge: "2 products", image: "./img/products/gemini.webp", link: "#",
    subProducts: [
      { id: 1131, title: "Gemini Pro+ Keys 12 Months [Own Account]", slug: "gemini-pro-keys-12-months-own-account", priceText: "ARS 9.243", badge: "En stock", image: "./img/products/gemini.webp", description: "Gemini Advanced / Pro+ - Inteligencia Artificial de Google con 33Store.\nLlevá tu productividad al siguiente nivel con el modelo más potente de Google directamente en tu propia cuenta.\n\nCARACTERÍSTICAS DEL SERVICIO\n  En Tu Propia Cuenta: Activamos la suscripción premium directamente en tu correo personal.\n  Acceso a Gemini Advanced: Respuestas más precisas, razonamiento lógico complejo y creación de código avanzado.\n  Garantía 33Store: Cobertura total durante todo el período contratado.\n\nCALIDAD Y ENTREGA\n  Seguridad Total: El proceso de activación es 100% seguro y privado.\n  Sin Renovaciones Automáticas Sorpresa: Pagás por el tiempo pactado y lo usás sin preocupaciones.\n\nSOPORTE\n  Soporte en español y resolución de consultas a través del equipo de 33Store." },
      { id: 1132, title: "Gemini Pro+ Keys 18 Months [Own Account]", slug: "gemini-pro-keys-18-months-own-account", priceText: "ARS 11.583", badge: "En stock", image: "./img/products/gemini.webp", description: "Gemini Advanced / Pro+ - Inteligencia Artificial de Google con 33Store.\nLlevá tu productividad al siguiente nivel con el modelo más potente de Google directamente en tu propia cuenta.\n\nCARACTERÍSTICAS DEL SERVICIO\n  En Tu Propia Cuenta: Activamos la suscripción premium directamente en tu correo personal.\n  Acceso a Gemini Advanced: Respuestas más precisas, razonamiento lógico complejo y creación de código avanzado.\n  Garantía 33Store: Cobertura total durante todo el período contratado.\n\nCALIDAD Y ENTREGA\n  Seguridad Total: El proceso de activación es 100% seguro y privado.\n  Sin Renovaciones Automáticas Sorpresa: Pagás por el tiempo pactado y lo usás sin preocupaciones.\n\nSOPORTE\n  Soporte en español y resolución de consultas a través del equipo de 33Store." }
    ]
  },
  { 
    id: 114, category: "Streaming", title: "HBO Max", slug: "hbo-max", priceText: "ARS 423 - ARS 3.127", badge: "2 products", image: "./img/products/hbomax.webp", link: "#",
    subProducts: [
      { id: 1141, title: "HboMax Keys [Lifetime + Autoreplace]", slug: "hbomax-keys-lifetime-autoreplace", priceText: "ARS 4.329", badge: "En stock", image: "./img/products/hbomax.webp", description: "Max (ex HBO Max) Premium Lifetime - Cine y Series de por Vida con 33Store.\nAccedé a todo el contenido exclusivo de HBO, Warner Bros y DC con un único pago definitivo.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único: Sin suscripciones mensuales. Pagás hoy y disfrutás sin vencimiento.\n  Máxima Calidad: Streaming fluido y en la más alta resolución disponible (según dispositivo).\n  Garantía Lifetime 33Store: Nuestro sistema Auto Replace asegura un reemplazo al instante si la cuenta original llega a presentar cambios.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Recibís los datos de acceso al instante de confirmar tu compra.\n  Acceso Asegurado: Disfrutá desde tus dispositivos favoritos (Smart TV, Celular, PC).\n\nSOPORTE\n  Soporte técnico 24/7 de 33Store para solucionar dudas o realizar reposiciones si es necesario." },
      { id: 1142, title: "HboMax Lifetime", slug: "hbomax-lifetime", priceText: "ARS 585", badge: "En stock", image: "./img/products/hbomax.webp", description: "Max (ex HBO Max) Premium Lifetime - Cine y Series de por Vida con 33Store.\nAccedé a todo el contenido exclusivo de HBO, Warner Bros y DC con un único pago definitivo.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único: Sin suscripciones mensuales. Pagás hoy y disfrutás sin vencimiento.\n  Máxima Calidad: Streaming fluido y en la más alta resolución disponible (según dispositivo).\n  Garantía Lifetime 33Store: Nuestro sistema Auto Replace asegura un reemplazo al instante si la cuenta original llega a presentar cambios.\n\nCALIDAD Y ENTREGA\n  Activación Inmediata: Recibís los datos de acceso al instante de confirmar tu compra.\n  Acceso Asegurado: Disfrutá desde tus dispositivos favoritos (Smart TV, Celular, PC).\n\nSOPORTE\n  Soporte técnico 24/7 de 33Store para solucionar dudas o realizar reposiciones si es necesario." }
    ]
  },
  { id: 115, category: "Software & Learning", title: "Microsoft Codes", slug: "microsoft-codes", priceText: "ARS 1.083", badge: "5 products", image: "./img/products/microsoftcodes.webp", link: "#", description: "Microsoft Random Codes - Códigos Digitales y Licencias con 33Store.\nObtené códigos y licencias de Microsoft para juegos, aplicaciones o contenido digital con entrega inmediata.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Códigos Oficiales: Códigos de activación listos para canjear en la tienda oficial de Microsoft / Xbox.\n  Variedad de Contenidos: Juegos, expansiones o créditos digitales.\n  Excelente Valor: Obtené más por tu dinero con las ofertas exclusivas de 33Store.\n\nCALIDAD Y ENTREGA\n  Entrega Instantánea: El código de activación te llega directo al confirmar la compra.\n  Garantía de Validez: 100% verificados antes de la entrega.\n\nSOPORTE\n  Soporte paso a paso para el canje oficial en tu cuenta de Microsoft." },
  { id: 116, category: "Gaming", title: "Minecraft Account", slug: "minecraft-account", priceText: "ARS 10.413", badge: "En stock", image: "./img/products/minecrtaft.webp", link: "#", description: "Minecraft Java & Bedrock Edition - Cuenta Full Access con 33Store.\nObtené tu cuenta oficial de Minecraft con acceso total (Full Access) para jugar en todos los servidores premium como Hypixel.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Cambiá correo, contraseña, skin y nick de la cuenta sin restricciones.\n  Ediciones Incluidas: Incluye acceso a Minecraft Java y Bedrock Edition en PC.\n  Acceso a Servidores Premium: Entrá a Hypixel, Mineplex y cualquier servidor oficial sin ban.\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática.\n  Garantía 33Store: Verificadas y respaldadas ante cualquier problema de acceso.\n\nSOPORTE\n  Guía de configuración y soporte directo ante cualquier duda." },
  { id: 117, category: "Streaming", title: "Movistar+", slug: "movistar", priceText: "ARS 2.000", badge: "En stock", image: "./img/products/movistar+.webp", link: "#", description: "Movistar+ Lifetime - Disfrutá de todo el contenido exclusivo de Movistar+ con 33Store.\nSeries, películas y programas de TV.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Contenido Exclusivo: Las mejores producciones originales y cine de estreno.\n  Calidad HD: Streaming fluido en todos tus dispositivos.\n\nCALIDAD Y ENTREGA\n  Pago Único (Lifetime): Un solo pago para acceso prolongado sin mensualidades.\n  Entrega Inmediata: Credenciales directas enviadas al instante.\n\nSOPORTE\n  Respaldo de 33Store con atención prioritaria." },
  { id: 118, category: "Sports Streaming", title: "NBA Pass Lifetime", slug: "nba-pass-lifetime", priceText: "ARS 1.000", badge: "En stock", image: "./img/products/nba.webp", link: "#", description: "NBA League Pass Lifetime - Toda la Temporada de la NBA con 33Store.\nViví todos los partidos de la NBA en vivo y en HD, desde la temporada regular hasta los Playoffs y las Finales.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Todos los Partidos en Vivo: Transmisión en HD con relatos en español e inglés.\n  Repeticiones Completa & Highlights: Reviví partidos históricos o resúmenes al instante.\n  Multi-Pantalla: Mirá desde tu Smart TV, PC, tablet o celular.\n\nCALIDAD Y ENTREGA\n  Pago Único (Lifetime): Disfrutá de la pasión del básquetbol sin cuotas mensuales.\n  Garantía 33Store: Sistema de reposición automática ante cualquier inconveniente.\n\nSOPORTE\n  Soporte 24/7 dedicado a que no te pierdas ningún juego importante." },
  { 
    id: 119, category: "Streaming", title: "Netflix Lifetime", slug: "netflix-lifetime", priceText: "ARS 900 - ARS 6.903", badge: "5 products", image: "./img/products/netflix.webp", link: "#",
    subProducts: [
      { id: 1191, title: "Netflix Lifetime Keys 4K Plan [Lifetime Warranty + Auto Replace]", slug: "netflix-lifetime-keys-4k-plan-lifetime-warranty-auto-replace", priceText: "ARS 6.903", badge: "En stock", image: "./img/products/netflix.webp", description: "Netflix Premium de por Vida - Entretenimiento Ilimitado con 33Store.\nDisfrutá del catálogo completo de Netflix en máxima calidad con un solo pago y sin cuotas mensuales.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único: Olvidate de pagar mes a mes. Disfrutá sin vencimiento fijo.\n  Calidad de Imagen: Opciones desde HD hasta 4K Ultra HD según la variante elegida.\n  Garantía Lifetime 33Store: Sistema de auto-reemplazo (Auto Replace) que garantiza que siempre tengas una cuenta funcional si elegís los planes premium.\n\nCALIDAD Y ENTREGA\n  Activación Rápida: Recibís tus credenciales apenas se procesa el pedido.\n  Opciones Variadas: Desde perfiles Random hasta calidad UHQ o cuentas geolocalizadas.\n\nSOPORTE\n  Soporte 24/7. Si la cuenta llega a fallar, el equipo de 33Store o nuestro bot te resuelven el problema." },
      { id: 1192, title: "Netflix Lifetime Keys [Lifetime Warranty + Auto Replace]", slug: "netflix-lifetime-keys-lifetime-warranty-auto-replace", priceText: "ARS 3.500", badge: "En stock", image: "./img/products/netflix.webp", description: "Netflix Premium de por Vida - Entretenimiento Ilimitado con 33Store.\nDisfrutá del catálogo completo de Netflix en máxima calidad con un solo pago y sin cuotas mensuales.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único: Olvidate de pagar mes a mes. Disfrutá sin vencimiento fijo.\n  Calidad de Imagen: Opciones desde HD hasta 4K Ultra HD según la variante elegida.\n  Garantía Lifetime 33Store: Sistema de auto-reemplazo (Auto Replace) que garantiza que siempre tengas una cuenta funcional si elegís los planes premium.\n\nCALIDAD Y ENTREGA\n  Activación Rápida: Recibís tus credenciales apenas se procesa el pedido.\n  Opciones Variadas: Desde perfiles Random hasta calidad UHQ o cuentas geolocalizadas.\n\nSOPORTE\n  Soporte 24/7. Si la cuenta llega a fallar, el equipo de 33Store o nuestro bot te resuelven el problema." },
      { id: 1193, title: "Netflix Lifetime [Random Sub]", slug: "netflix-lifetime-random-sub", priceText: "ARS 900", badge: "En stock", image: "./img/products/netflix.webp", description: "Netflix Premium de por Vida - Entretenimiento Ilimitado con 33Store.\nDisfrutá del catálogo completo de Netflix en máxima calidad con un solo pago y sin cuotas mensuales.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único: Olvidate de pagar mes a mes. Disfrutá sin vencimiento fijo.\n  Calidad de Imagen: Opciones desde HD hasta 4K Ultra HD según la variante elegida.\n  Garantía Lifetime 33Store: Sistema de auto-reemplazo (Auto Replace) que garantiza que siempre tengas una cuenta funcional si elegís los planes premium.\n\nCALIDAD Y ENTREGA\n  Activación Rápida: Recibís tus credenciales apenas se procesa el pedido.\n  Opciones Variadas: Desde perfiles Random hasta calidad UHQ o cuentas geolocalizadas.\n\nSOPORTE\n  Soporte 24/7. Si la cuenta llega a fallar, el equipo de 33Store o nuestro bot te resuelven el problema." },
      { id: 1194, title: "Netflix Lifetime [UHQ]", slug: "netflix-lifetime-uhq", priceText: "ARS 2.500", badge: "En stock", image: "./img/products/netflix.webp", description: "Netflix Premium de por Vida - Entretenimiento Ilimitado con 33Store.\nDisfrutá del catálogo completo de Netflix en máxima calidad con un solo pago y sin cuotas mensuales.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Pago Único: Olvidate de pagar mes a mes. Disfrutá sin vencimiento fijo.\n  Calidad de Imagen: Opciones desde HD hasta 4K Ultra HD según la variante elegida.\n  Garantía Lifetime 33Store: Sistema de auto-reemplazo (Auto Replace) que garantiza que siempre tengas una cuenta funcional si elegís los planes premium.\n\nCALIDAD Y ENTREGA\n  Activación Rápida: Recibís tus credenciales apenas se procesa el pedido.\n  Opciones Variadas: Desde perfiles Random hasta calidad UHQ o cuentas geolocalizadas.\n\nSOPORTE\n  Soporte 24/7. Si la cuenta llega a fallar, el equipo de 33Store o nuestro bot te resuelven el problema." }
    ]
  },
  { id: 120, category: "VPN & Security", title: "NordVPN Lifetime", slug: "nordvpn-lifetime", priceText: "ARS 1.400", badge: "En stock", image: "./img/products/nordvpn.webp", link: "#", description: "NordVPN Premium Lifetime - Seguridad Digital Avanzada con 33Store.\nProtegé tu conexión con la tecnología Meshnet, protección contra amenazas y más de 5500 servidores rápidos en todo el mundo.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Protección contra Amenazas: Bloqueo integrado de anuncios, trackers y malware.\n  Conexión Ultra Rápida: Protocolo NordLynx para gaming y streaming en 4K sin lag.\n  Privacidad Estricta: Política verificada de no-registros (No-Logs).\n\nCALIDAD Y ENTREGA\n  Uso Multi-Plataforma: Funciona en PC, móviles, routers y Smart TV.\n  Garantía Lifetime 33Store: Cobertura total con reemplazos instantáneos si es necesario.\n\nSOPORTE\n  Soporte técnico listo para ayudarte a configurar tus dispositivos." },
  { id: 121, category: "Streaming", title: "Paramount+", slug: "paramount", priceText: "ARS 1.000", badge: "En stock", image: "./img/products/paramount+.webp", link: "#", description: "Paramount+ Lifetime - Cine, Series Exclusivas y Deportes con 33Store.\nDisfrutá del catálogo de Paramount, Showtime, Nickelodeon, MTV y torneos deportivos exclusivos como la CONMEBOL Libertadores.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Contenido Exclusivo: Películas de estreno, series originales y clásicos de Nickelodeon y MTV.\n  Deportes en Vivo: Transmisiones deportivas de primer nivel sin costo adicional.\n  Calidad HD / 4K: Streaming fluido en todos tus dispositivos.\n\nCALIDAD Y ENTREGA\n  Pago Único (Lifetime): Un solo pago para acceso prolongado sin mensualidades.\n  Entrega Inmediata: Credenciales directas enviadas al instante.\n\nSOPORTE\n  Respaldo de 33Store con atención prioritaria ante cualquier duda." },
  { 
    id: 122, category: "Streaming", title: "Prime Video", slug: "prime-video", priceText: "ARS 2.500 - ARS 7.500", badge: "2 products", image: "./img/products/primevideo.webp", link: "#",
    subProducts: [
      { id: 1221, title: "Prime Video Head FA [1 month]", slug: "prime-video-head-fa-1-month", priceText: "ARS 2.500", badge: "En stock", image: "./img/products/primevideo.webp" },
      { id: 1222, title: "Prime Video FA [6 months]", slug: "prime-video-fa-6-months", priceText: "ARS 7.500", badge: "En stock", image: "./img/products/primevideo.webp" }
    ]
  },
  { 
    id: 123, category: "Social Media Growth", title: "Social Boost", slug: "social-boost", priceText: "ARS 1.352 - ARS 6.760", badge: "7 products", image: "./img/products/socialboost.webp", link: "#",
    subProducts: [
      { id: 1231, title: "Instagram Boost", slug: "instagram-boost", priceText: "ARS 23,40", badge: "En stock", image: "./img/socialboost/instagram.webp" , description: "Servicios de Crecimiento en Instagram\\nInteracciones Premium de Instagram para perfiles, publicaciones, Reels y videos con procesamiento rápido y automatizado.\\n\\nCARACTERÍSTICAS DEL SERVICIO\\n• Elige entre visualizaciones, me gusta y seguidores.\\n• Cantidades flexibles con límites mínimos y máximos claros.\\n• Inicio rápido y alta capacidad de entrega.\\n\\nCALIDAD Y ENTREGA\\n• Los servicios son seleccionados por su gran valor, estabilidad y rendimiento confiable.\\n• Los pedidos se envían automáticamente después del pago.\\n• Se requiere un enlace público válido de Instagram.\\n• Mantén el perfil, publicación, Reel o video público hasta que se complete la entrega.\\n\\nSOPORTE\\n• Soporte disponible para problemas relacionados con el pedido.", variants: [{"name":"Visualizaciones","priceText":"ARS 23,40 c/u","desc":"Reels y videos · Sin caídas", "minQty": 1000, "priceNum": 23.4},{"name":"Me Gusta","priceText":"ARS 23,40 c/u","desc":"Cuentas reales · Baja caída", "minQty": 1000, "priceNum": 23.4},{"name":"Seguidores","priceText":"ARS 23,40 c/u","desc":"Cuentas con publicaciones · Sin caídas", "minQty": 1000, "priceNum": 23.4}] },
      { id: 1232, title: "TikTok Boost", slug: "tiktok-boost", priceText: "ARS 23,40", badge: "En stock", image: "./img/socialboost/tiktok.webp" , description: "Servicios de Crecimiento en TikTok\\nInteracciones de alta calidad para videos y perfiles de TikTok, procesadas automáticamente después del pago.\\n\\nCARACTERÍSTICAS DEL SERVICIO\\n• Elige entre visualizaciones de video, me gusta y seguidores.\\n• Inicio rápido con velocidades de entrega escalables.\\n• Cuentas reales o de alta calidad donde se indique.\\n\\nCALIDAD Y ENTREGA\\n• Seleccionados por su confiabilidad, velocidad y valor competitivo.\\n• Ingresa el enlace público correcto del video o perfil de TikTok.\\n• Mantén el contenido y la cuenta públicos durante la entrega.\\n• No realices otro pedido para el mismo enlace hasta que se complete el primero.\\n\\nSOPORTE\\n• Soporte disponible para problemas funcionales del pedido.", variants: [{"name":"Visualizaciones","priceText":"ARS 23,40 c/u","desc":"Inicio rápido · Baja caída · Hasta 10M/día", "minQty": 1000, "priceNum": 23.4},{"name":"Me Gusta","priceText":"ARS 23,40 c/u","desc":"Cuentas de alta calidad · Inicio instantáneo", "minQty": 1000, "priceNum": 23.4},{"name":"Seguidores","priceText":"ARS 23,40 c/u","desc":"Cuentas reales · Caída muy baja", "minQty": 1000, "priceNum": 23.4}] },
      { id: 1233, title: "X (Twitter) Boost", slug: "x-twitter-boost", priceText: "ARS 23,40", badge: "En stock", image: "./img/socialboost/x.webp" , description: "Servicios de Crecimiento en X / Twitter\\nInteracciones profesionales para perfiles, publicaciones y videos de X con procesamiento automático rápido.\\n\\nCARACTERÍSTICAS DEL SERVICIO\\n• Elige entre visualizaciones, me gusta y seguidores.\\n• Compatible con publicaciones y contenido de video donde se indique.\\n• Se utilizan perfiles reales o de alta calidad para los servicios de seguidores y me gusta.\\n\\nCALIDAD Y ENTREGA\\n• Seleccionados por su velocidad, estabilidad y gran valor.\\n• Ingresa la URL pública correcta de la publicación, video o perfil.\\n• Mantén la cuenta y el contenido públicos hasta su finalización.\\n• Evita cambiar nombres de usuario o eliminar contenido durante la entrega.\\n\\nSOPORTE\\n• Soporte disponible para problemas funcionales del pedido.", variants: [{"name":"Visualizaciones","priceText":"ARS 23,40 c/u","desc":"Publicaciones y videos · Inicio instantáneo", "minQty": 1000, "priceNum": 23.4},{"name":"Me Gusta","priceText":"ARS 23,40 c/u","desc":"Cuentas de alta calidad · Baja caída", "minQty": 1000, "priceNum": 23.4},{"name":"Seguidores","priceText":"ARS 23,40 c/u","desc":"Perfiles reales · Baja caída", "minQty": 1000, "priceNum": 23.4}] },
      { id: 1234, title: "Facebook Boost", slug: "facebook-boost", priceText: "ARS 23,40", badge: "En stock", image: "./img/socialboost/facebook.webp" , description: "Servicios de Crecimiento en Facebook\\nInteracciones de alta calidad en Facebook para perfiles, páginas y Reels con procesamiento automático.\\n\\nCARACTERÍSTICAS DEL SERVICIO\\n• Elige entre visualizaciones de Reels y seguidores.\\n• Compatible con perfiles y páginas de Facebook donde se indique.\\n• Cantidades flexibles para diferentes tamaños de campaña.\\n\\nCALIDAD Y ENTREGA\\n• Seleccionados por su confiabilidad, velocidad y precios competitivos.\\n• Ingresa la URL pública correcta del perfil, página o Reel.\\n• Mantén el destino público durante la entrega.\\n• No elimines ni restrinjas el contenido antes de su finalización.\\n\\nSOPORTE\\n• Soporte disponible para problemas funcionales del pedido.", variants: [{"name":"Visualizaciones de Reels","priceText":"ARS 23,40 c/u","desc":"Alta calidad · Entrega rápida", "minQty": 1000, "priceNum": 23.4},{"name":"Seguidores","priceText":"ARS 23,40 c/u","desc":"Perfiles y páginas · Cuentas de alta calidad", "minQty": 1000, "priceNum": 23.4}] },
      { id: 1235, title: "YouTube Boost", slug: "youtube-boost", priceText: "ARS 11,70 - ARS 187,20", badge: "En stock", image: "./img/socialboost/youtube.webp" , description: "Servicios de Crecimiento en YouTube\nInteracciones confiables en YouTube para videos, Shorts y canales con procesamiento automático de pedidos.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Elige entre visualizaciones, me gusta, suscriptores y comentarios personalizados.\n  Adecuado para videos, Shorts y crecimiento de canales.\n  Cantidades flexibles para campañas pequeñas y grandes.\n\nCALIDAD Y ENTREGA\n  Seleccionados por su rendimiento estable y precios competitivos.\n  Ingresa la URL pública correcta del video, Short o canal.\n  Mantén el contenido público y no cambies la URL durante la entrega.\n  La velocidad de entrega puede variar según el tamaño del pedido y la actividad de la plataforma.\n\nSOPORTE\n  Soporte disponible para problemas relacionados con el pedido.", variants: [{"name":"Visualizaciones","priceText":"ARS 23,40 c/u","desc":"Videos y Shorts · Sin caídas", "minQty": 1000, "priceNum": 23.4},{"name":"Me Gusta HQ","priceText":"ARS 11,70 c/u","desc":"Me gusta de alta calidad", "minQty": 1000, "priceNum": 11.7},{"name":"Suscriptores HQ","priceText":"ARS 187,20 c/u","desc":"Alta calidad · Estables", "minQty": 1000, "priceNum": 187.2},{"name":"Comentarios Personalizados","priceText":"ARS 23,40 c/u","desc":"Interacciones personalizadas", "minQty": 1000, "priceNum": 23.4}] },
      { id: 1236, title: "Telegram Boost", slug: "telegram-boost", priceText: "ARS 11,70 - ARS 81,90", badge: "En stock", image: "./img/socialboost/telegram.webp" , description: "Servicios de Crecimiento en Telegram\nInteracciones rápidas en Telegram para canales, grupos y publicaciones con entrega automática.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Elige entre miembros del canal o grupo, visualizaciones de publicaciones y reacciones.\n  Inicio rápido y alta capacidad de entrega.\n  Los servicios de visualización están diseñados para la última publicación elegible o envíos automáticos.\n\nCALIDAD Y ENTREGA\n  Seleccionados por su rendimiento confiable y valor competitivo.\n  Ingresa un enlace público válido del canal, grupo o publicación de Telegram.\n  Mantén el destino accesible hasta que se complete la entrega.\n  Los enlaces de invitación privados o vencidos pueden impedir la entrega.\n\nSOPORTE\n  Soporte disponible para problemas relacionados con el pedido.", variants: [{"name":"Miembros Reales","priceText":"ARS 11,70 c/u","desc":"Para canales o grupos", "minQty": 1000, "priceNum": 11.7},{"name":"Visualizaciones","priceText":"ARS 11,70 c/u","desc":"Para un post público", "minQty": 1000, "priceNum": 11.7},{"name":"Reacciones","priceText":"ARS 11,70 c/u","desc":"Reacciones positivas mixtas", "minQty": 1000, "priceNum": 11.7},{"name":"Vistas Automáticas","priceText":"ARS 11,70 c/u","desc":"Próximos 5 posts", "minQty": 1000, "priceNum": 11.7},{"name":"Miembros Premium","priceText":"ARS 81,90 c/u","desc":"Garantía de 14 días", "minQty": 1000, "priceNum": 81.9}] },
      { id: 1237, title: "Spotify Boost", slug: "spotify-boost", priceText: "ARS 23,40", badge: "En stock", image: "./img/socialboost/spotify.webp" , description: "Servicios de Crecimiento en Spotify\\nPromoción Premium en Spotify para artistas, canciones, listas de reproducción, álbumes y perfiles de usuario.\\n\\nCARACTERÍSTICAS DEL SERVICIO\\n• Elige entre seguidores y reproducciones premium de EE. UU.\\n• Admite artistas, usuarios, listas, canciones y álbumes elegibles.\\n• Inicio rápido con capacidad de entrega escalable.\\n\\nCALIDAD Y ENTREGA\\n• Seleccionados por su rendimiento estable y gran valor.\\n• Ingresa la URL pública exacta de Spotify para el destino seleccionado.\\n• Mantén la canción, artista, lista de reproducción, álbum o perfil disponible durante la entrega.\\n• La velocidad de entrega puede variar según el tamaño de la campaña.\\n\\nSOPORTE\\n• Soporte disponible para problemas relacionados con el pedido.", variants: [{"name":"Seguidores","priceText":"ARS 23,40 c/u","desc":"Artistas, usuarios y listas de reproducción", "minQty": 1000, "priceNum": 23.4},{"name":"Reproducciones USA","priceText":"ARS 23,40 c/u","desc":"Reproducciones premium de EE. UU. · Canciones, artistas, listas y álbumes", "minQty": 1000, "priceNum": 23.4}] }
    ]
  },
  { 
    id: 124, category: "Music", title: "Spotify Premium", slug: "spotify-premium", priceText: "ARS 2.270 - ARS 14.017", badge: "4 products", image: "./img/products/spotify.webp", link: "#",
    subProducts: [
      { id: 1241, title: "Spotify Premium Keys [12 Months]", slug: "spotify-premium-keys-12-months", priceText: "ARS 8.775", badge: "En stock", image: "./img/products/spotify.webp" },
      { id: 1242, title: "Spotify Premium Keys [Lifetime + Autoreplace]", slug: "spotify-premium-keys-lifetime-autoreplace", priceText: "ARS 14.017", badge: "En stock", image: "./img/products/spotify.webp" },
      { id: 1243, title: "Spotify Premium FA [1 month]", slug: "spotify-premium-fa-1-month", priceText: "ARS 2.270", badge: "En stock", image: "./img/products/spotify.webp" },
      { id: 1244, title: "Spotify Premium FA [AUTOPAY]", slug: "spotify-premium-fa-autopay", priceText: "ARS 9.243", badge: "En stock", image: "./img/products/spotify.webp" }
    ]
  },
  { 
    id: 125, category: "Gaming", title: "Steam Accounts", slug: "steam-accounts", priceText: "ARS 47 - ARS 16.088", badge: "20 products", image: "./img/products/steam.webp", link: "#",
    subProducts: [
      { id: 1251, title: "Steam Lifetime [0-3 games]", slug: "steam-lifetime-0-3-games", priceText: "ARS 47", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1252, title: "Steam Lifetime [+4 Games & Balance]", slug: "steam-lifetime-4-games-balance", priceText: "ARS 140", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1253, title: "Steam Lifetime [Counter Strike]", slug: "steam-lifetime-counter-strike", priceText: "ARS 130", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1254, title: "Steam Lifetime [GTA 5]", slug: "steam-lifetime-gta-5", priceText: "ARS 1.750", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1255, title: "Steam Lifetime [Rainbow Six]", slug: "steam-lifetime-rainbow-six", priceText: "ARS 1.750", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1256, title: "Steam Lifetime [Among Us]", slug: "steam-lifetime-among-us", priceText: "ARS 365", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1257, title: "Steam Lifetime [Schedule I]", slug: "steam-lifetime-schedule-i", priceText: "ARS 11.176", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1258, title: "Steam Lifetime [Assetto Corsa]", slug: "steam-lifetime-assetto-corsa", priceText: "ARS 494", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1259, title: "Steam Lifetime [FC 26]", slug: "steam-lifetime-fc-26", priceText: "ARS 16.088", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1260, title: "Steam Lifetime [Euro Truck Simulator 2]", slug: "steam-lifetime-euro-truck-simulator-2", priceText: "ARS 515", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1261, title: "Steam Lifetime [Red Dead Redemption 2]", slug: "steam-lifetime-red-dead-redemption-2", priceText: "ARS 13.621", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1262, title: "Steam Lifetime [Supermarket Simulator]", slug: "steam-lifetime-supermarket-simulator", priceText: "ARS 1.867", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1263, title: "Steam Lifetime [Rainbow Six]", slug: "steam-lifetime-rainbow-six-new", priceText: "ARS 1.750", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1264, title: "Steam Lifetime [Forza Horizon 5]", slug: "steam-lifetime-forza-horizon-5", priceText: "ARS 8.816", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1265, title: "Steam Lifetime [Ready or Not]", slug: "steam-lifetime-ready-or-not", priceText: "ARS 5.835", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1266, title: "Steam Lifetime [Resident Evil Village]", slug: "steam-lifetime-resident-evil-village", priceText: "ARS 365", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1267, title: "Steam Lifetime [Cyberpunk 2077]", slug: "steam-lifetime-cyberpunk-2077", priceText: "ARS 8.688", badge: "Agotado", image: "./img/products/steam.webp" },
      { id: 1268, title: "Steam Lifetime [Wallpaper Engine]", slug: "steam-lifetime-wallpaper-engine", priceText: "ARS 858", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1269, title: "Steam Lifetime [Marvel Rivals]", slug: "steam-lifetime-marvel-rivals", priceText: "ARS 151", badge: "En stock", image: "./img/products/steam.webp" },
      { id: 1270, title: "Steam Lifetime [Rust]", slug: "steam-lifetime-rust", priceText: "ARS 1.609", badge: "En stock", image: "./img/products/steam.webp" }
    ]
  },
  { 
    id: 126, category: "Food & Discounts", title: "Telepizza", slug: "telepizza", priceText: "ARS 585 - ARS 2.223", badge: "2 products", image: "./img/products/telepizza.webp", link: "#",
    subProducts: [
      { id: 1261, title: "Telepizza [500-4K POINTS]", slug: "telepizza-500-4k-points", priceText: "ARS 585", badge: "En stock", image: "./img/products/telepizza.webp", description: "Telepizza Puntos - Disfrutá de la Mejor Pizza con 33Store.\nCuentas cargadas con puntos listos para canjear por pizzas, entradas y bebidas en tus sucursales favoritas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Puntos Listos para Usar: Comprá una cuenta y usá los puntos inmediatamente desde la app oficial de Telepizza.\n  Diferentes Saldos: Elegí cuentas desde 500 puntos hasta más de 90k puntos según el banquete que quieras armar.\n  Ahorro Masivo: Comés mucho más por una fracción del precio real.\n\nCALIDAD Y ENTREGA\n  Entrega Automática: Recibís el usuario y contraseña (Email:Pass) de la cuenta con los puntos.\n  Garantía de Saldo: Garantizamos que la cuenta tendrá exactamente los puntos que compraste al momento de la entrega.\n\nSOPORTE\n  Soporte 33Store. Debés revisar la cuenta dentro de los primeros 15 minutos de la entrega para validar la garantía." },
      { id: 1262, title: "Telepizza [4K-90K POINTS]", slug: "telepizza-4k-90k-points", priceText: "ARS 2.223", badge: "En stock", image: "./img/products/telepizza.webp", description: "Telepizza Puntos - Disfrutá de la Mejor Pizza con 33Store.\nCuentas cargadas con puntos listos para canjear por pizzas, entradas y bebidas en tus sucursales favoritas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Puntos Listos para Usar: Comprá una cuenta y usá los puntos inmediatamente desde la app oficial de Telepizza.\n  Diferentes Saldos: Elegí cuentas desde 500 puntos hasta más de 90k puntos según el banquete que quieras armar.\n  Ahorro Masivo: Comés mucho más por una fracción del precio real.\n\nCALIDAD Y ENTREGA\n  Entrega Automática: Recibís el usuario y contraseña (Email:Pass) de la cuenta con los puntos.\n  Garantía de Saldo: Garantizamos que la cuenta tendrá exactamente los puntos que compraste al momento de la entrega.\n\nSOPORTE\n  Soporte 33Store. Debés revisar la cuenta dentro de los primeros 15 minutos de la entrega para validar la garantía." }
    ]
  },
  { id: 127, category: "Food & Discounts", title: "Uber Eats", slug: "uber-eats", priceText: "ARS 9.243", badge: "En stock", image: "./img/products/ubereats.webp", link: "#", description: "Uber Eats Discounts & Accounts - Descuentos Masivos en Comida con 33Store.\nAhorrá a lo grande en tus pedidos de delivery en restaurantes y supermercados favoritos.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Descuentos Exclusivos: Cuentas cargadas con promociones y cupones de alto valor.\n  Ahorro Real: Pedí comida gourmet por una fracción de su costo de lista.\n  Uso Sencillo: Ingresá la cuenta y realizá tu pedido directamente en la app de Uber Eats.\n\nCALIDAD Y ENTREGA\n  Entrega Instantánea: Datos de la cuenta (Email:Pass) entregados de inmediato tras el pago.\n  Garantía de Saldo: Garantizamos que la cuenta cuenta con las promociones activas al momento de la entrega.\n\nSOPORTE\n  Revisión y garantía durante los primeros minutos de entrega respaldada por 33Store." },
  { id: 128, category: "Sports Streaming", title: "UFC Pass Lifetime", slug: "ufc-pass-lifetime", priceText: "ARS 1.750", badge: "En stock", image: "./img/products/ufc.webp", link: "#", description: "UFC Fight Pass Lifetime - Todo el Combate en Vivo con 33Store.\nAccedé a todos los eventos de UFC (Fight Nights, Preliminares), la biblioteca histórica de artes marciales mixtas y transmisiones en vivo.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Eventos en Vivo & On Demand: Viví la emoción de las MMA, kickboxing, submission grappling y más.\n  Biblioteca Histórica: Acceso ilimitado a todas las peleas en la historia de la UFC, PRIDE, Strikeforce y WEC.\n  Calidad Full HD: Transmisiones limpias y en la más alta resolución.\n\nCALIDAD Y ENTREGA\n  Pago Único (Lifetime): Disfrutá de todos los combates de por vida sin membresías mensuales.\n  Garantía 33Store: Reemplazo automatizado en caso de caídas o ajustes de plataforma.\n\nSOPORTE\n  Atención 24/7 por el equipo de 33Store para que disfrutes cada evento sin interrupciones." },
  { 
    id: 129, category: "Streaming", title: "YouTube Premium", slug: "youtube-premium", priceText: "ARS 2.223 - ARS 6.903", badge: "4 products", image: "./img/products/youtubepremium.webp", link: "#",
    subProducts: [
      { id: 1291, title: "Youtube Premium Keys [ Your Own Account ]", slug: "youtube-premium-keys-your-own-account", priceText: "ARS 2.925", badge: "En stock", image: "./img/products/youtubepremium.webp" },
      { id: 1292, title: "Youtube Premium Family Owner Keys [ Your Own Account ]", slug: "youtube-premium-family-owner-keys-your-own-account", priceText: "ARS 4.563", badge: "En stock", image: "./img/products/youtubepremium.webp" },
      { id: 1293, title: "Youtube Premium FA [1 Month]", slug: "youtube-premium-fa-1-month", priceText: "ARS 2.223", badge: "En stock", image: "./img/products/youtubepremium.webp" },
      { id: 1294, title: "Youtube Premium FA [3 Months]", slug: "youtube-premium-fa-3-months", priceText: "ARS 6.903", badge: "En stock", image: "./img/products/youtubepremium.webp" }
    ]
  },
  { 
    id: 130, category: "Gaming", title: "Monedas de Juegos", slug: "monedas-de-juegos", priceText: "ARS 5.363", badge: "5 products", image: "./img/products/monedas_juegos.jpg", link: "#",
    subProducts: [
      { id: 1301, title: "V-Bucks Fortnite", slug: "v-bucks-fortnite", priceText: "ARS 5.363", badge: "En stock", image: "./img/products/vbucks.jpg", description: "V-Bucks para Fortnite.\\nRecarga automática de V-Bucks a tu cuenta.\\n\\nCARACTERÍSTICAS\\n• Entrega rápida y segura.\\n• Soporte para todas las plataformas (PC, Xbox, PS, Switch, Mobile).", variants: [{"name":"Monedas","priceText":"ARS 5.363 c/u","desc":"Min. 8000 | 1000 Monedas = $3.60 USD","minQty": 8000, "priceNum": 5.363}] },
      { id: 1302, title: "Robux", slug: "robux", priceText: "ARS 5.363", badge: "En stock", image: "./img/products/robux.jpg", description: "Robux para Roblox.\\nConsigue Robux de forma rápida.\\n\\nCARACTERÍSTICAS\\n• Entrega mediante Gamepass o Grupo (según disponibilidad).", variants: [{"name":"Monedas","priceText":"ARS 5.363 c/u","desc":"Min. 8000 | 1000 Monedas = $3.60 USD","minQty": 8000, "priceNum": 5.363}] },
      { id: 1303, title: "Rocket League Points", slug: "rocket-league-points", priceText: "ARS 5.363", badge: "En stock", image: "./img/products/rocket_league.jpg", description: "Créditos para Rocket League.\\n\\nCARACTERÍSTICAS\\n• Tradeo seguro in-game.", variants: [{"name":"Monedas","priceText":"ARS 5.363 c/u","desc":"Min. 8000 | 1000 Monedas = $3.60 USD","minQty": 8000, "priceNum": 5.363}] },
      { id: 1304, title: "Riot Points", slug: "riot-points", priceText: "ARS 5.363", badge: "En stock", image: "./img/products/riot_points.jpg", description: "Riot Points (RP) para League of Legends / TFT.\\n\\nCARACTERÍSTICAS\\n• Códigos o recarga directa según región.", variants: [{"name":"Monedas","priceText":"ARS 5.363 c/u","desc":"Min. 8000 | 1000 Monedas = $3.60 USD","minQty": 8000, "priceNum": 5.363}] },
      { id: 1305, title: "Valorant Points", slug: "valorant-points", priceText: "ARS 5.363", badge: "En stock", image: "./img/products/valorant_points.jpg", description: "Valorant Points (VP) para Valorant.\\n\\nCARACTERÍSTICAS\\n• Códigos globales o específicos por región.", variants: [{"name":"Monedas","priceText":"ARS 5.363 c/u","desc":"Min. 8000 | 1000 Monedas = $3.60 USD","minQty": 8000, "priceNum": 5.363}] }
    ]
  },
  { 
    id: 140, category: "Gaming", title: "Cuentas Fortnite", slug: "cuentas-fortnite", priceText: "ARS 1.609 - ARS 138.589", badge: "15 products", image: "./img/products/fortnite.webp", link: "#",
    subProducts: [
      { id: 1401, title: "[ FN ] 3-10 Skins [ Ranked Ready ]", slug: "fn-3-10-skins-ranked-ready", priceText: "ARS 1.609", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1402, title: "[ FN ] 10-20 Skins", slug: "fn-10-20-skins", priceText: "ARS 3.840", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1403, title: "[ FN ] 20-50 Skins", slug: "fn-20-50-skins", priceText: "ARS 6.071", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1404, title: "[ FN OG ] 50-100 Skins", slug: "fn-og-50-100-skins", priceText: "ARS 9.674", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1405, title: "[ FN OG ] 100-150 Skins", slug: "fn-og-100-150-skins", priceText: "ARS 19.241", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1406, title: "[ FN Tryhard ] 100-250 Skins", slug: "fn-tryhard-100-250-skins", priceText: "ARS 24.689", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1407, title: "[ FN OG ] 150-250 Skins", slug: "fn-og-150-250-skins", priceText: "ARS 28.915", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1408, title: "[ FN OG STW ] 100-200 Skins", slug: "fn-og-stw-100-200-skins", priceText: "ARS 29.902", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1409, title: "[ FN Leviathan Axe ] 50-150 Skins", slug: "fn-leviathan-axe-50-150-skins", priceText: "ARS 45.281", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1410, title: "[ FN OG ] 250-400 Skins", slug: "fn-og-250-400-skins", priceText: "ARS 47.641", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1411, title: "[ FN 1000 Level / +14 Events ] Tournament Ready", slug: "fn-1000-level-14-events-tournament-ready", priceText: "ARS 46.397", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1412, title: "[ FN OG Minty Axe ] 50-200 Skins", slug: "fn-og-minty-axe-50-200-skins", priceText: "ARS 48.263", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1413, title: "[ FN Travis Scott ] 100-250 Skins", slug: "fn-travis-scott-100-250-skins", priceText: "ARS 64.157", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1414, title: "[ FN OG ] 400-600 Skins", slug: "fn-og-400-600-skins", priceText: "ARS 85.607", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." },
      { id: 1415, title: "[ FN Black Knight ] 50-250 Skins", slug: "fn-black-knight-50-250-skins", priceText: "ARS 138.589", badge: "En stock", image: "./img/products/fortnite.webp", description: "Cuentas de Fortnite - Epic Games\nAdquirí tu cuenta de Fortnite con acceso completo y skins exclusivas.\n\nCARACTERÍSTICAS DEL SERVICIO\n  Full Access (FA): Podés cambiar el correo, la contraseña y el nombre de usuario de la cuenta sin restricciones.\n  Skins y Cosméticos: La cuenta incluye la cantidad de skins y características mencionadas en el título.\n  Plataformas: Vinculable a PC, PlayStation, Xbox, Nintendo Switch y dispositivos móviles (sujeto a restricciones de Epic Games).\n\nCALIDAD Y ENTREGA\n  Entrega Inmediata: Credenciales completas (Email:Pass) entregadas de forma automática al confirmar tu pago.\n  Garantía 33Store: Todas las cuentas son verificadas antes de la entrega.\n\nSOPORTE\n  Guía de seguridad y configuración inicial incluida. Soporte directo ante cualquier duda." }
    ]
  }
];

// Helper to parse price string to number for sorting
const parsePrice = (priceStr) => {
  // Ej: "ARS 1.235 - ARS 3.835" -> tomamos el primer numero "1.235"
  const match = priceStr.match(/ARS ([\d\.]+)/);
  if (match) {
    return parseInt(match[1].replace(/\./g, ''), 10);
  }
  return 0;
};

document.addEventListener('DOMContentLoaded', () => {
  const grid = document.getElementById('premium-grid');
  const modalOverlay = document.getElementById('subproduct-modal-overlay');
  const modal = document.getElementById('subproduct-modal');
  const closeModalBtn = document.getElementById('close-modal');
  const modalGrid = document.getElementById('modal-grid');
  const modalTitle = document.getElementById('modal-title');

  const categoryFilter = document.getElementById('category-filter');
  const priceFilter = document.getElementById('price-filter');
  const searchInput = document.getElementById('search-input');
  const countEl = document.getElementById('product-count');

  if (!grid) return;

  const createCardHTML = (product) => `
    <div class="premium-badge" style="${product.badge === 'Out of stock' ? 'background: rgba(255,0,0,0.3); color: #ff6b6b;' : ''}">${product.badge}</div>
    <div class="premium-image-wrapper">
      <img src="${product.image}" alt="${product.title} image" style="width:100%; height:100%; object-fit: cover;">
    </div>
    <div class="premium-delivery">
      <i class="fa-solid fa-bolt"></i> Entrega inmediata
    </div>
    <div class="premium-title">${product.title}</div>
    <div class="premium-price">${formatPriceText(product.priceText)}</div>
  `;

  const renderGrid = (productsToRender) => {
    grid.innerHTML = '';
    productsToRender.forEach(product => {
      const card = document.createElement('a');
      card.href = product.link;
      card.className = 'premium-card';
      card.innerHTML = createCardHTML(product);
      
      card.addEventListener('click', (e) => {
        e.preventDefault();
        if (product.subProducts && product.subProducts.length > 0) {
          openModal(product);
        } else {
          window.location.href = `/${product.slug}`;
        }
      });

      grid.appendChild(card);
    });
    
    if (countEl) {
      countEl.textContent = `${productsToRender.length} productos`;
    }
  };

  // Filter Logic
  const applyFilters = () => {
    const searchTerm = searchInput ? searchInput.value.toLowerCase() : '';
    const catValue = categoryFilter ? categoryFilter.value : 'all';
    const priceValue = priceFilter ? priceFilter.value : 'all';

    let filtered = premiumProducts;
    
    if (searchTerm !== '') {
      if (typeof Fuse !== 'undefined') {
        const fuse = new Fuse(filtered, {
          keys: ['title', 'description', 'category'],
          threshold: 0.4,
          distance: 100
        });
        filtered = fuse.search(searchTerm).map(res => res.item);
      } else {
        filtered = filtered.filter(p => p.title.toLowerCase().includes(searchTerm));
      }
    }
    
    filtered = filtered.filter(p => catValue === 'all' || p.category === catValue);

    if (priceValue === 'low') {
      filtered.sort((a, b) => parsePrice(a.priceText) - parsePrice(b.priceText));
    } else if (priceValue === 'high') {
      filtered.sort((a, b) => parsePrice(b.priceText) - parsePrice(a.priceText));
    }

    renderGrid(filtered);
  };

  if (searchInput) searchInput.addEventListener('input', applyFilters);
  if (categoryFilter) categoryFilter.addEventListener('change', applyFilters);
  if (priceFilter) priceFilter.addEventListener('change', applyFilters);

  // Initial render
  applyFilters();

  // Autocomplete Logic
  const autocompleteBox = document.getElementById('search-autocomplete');
  if (searchInput && autocompleteBox) {
    searchInput.addEventListener('input', (e) => {
      const term = e.target.value.toLowerCase();
      autocompleteBox.innerHTML = '';
      
      if (term.length < 2) {
        autocompleteBox.style.display = 'none';
        return;
      }

      let allProducts = [];
      premiumProducts.forEach(p => {
        if(p.subProducts) allProducts = allProducts.concat(p.subProducts);
        else allProducts.push(p);
      });

      let matches = [];
      if (typeof Fuse !== 'undefined') {
        const fuse = new Fuse(allProducts, {
          keys: ['title', 'description', 'category'],
          threshold: 0.4,
          distance: 100
        });
        matches = fuse.search(term).map(res => res.item).slice(0, 5);
      } else {
        matches = allProducts.filter(p => p.title.toLowerCase().includes(term)).slice(0, 5);
      }

      if (matches.length > 0) {
        autocompleteBox.style.display = 'block';
        matches.forEach(m => {
          const item = document.createElement('a');
          item.href = `/${m.slug}`;
          item.className = 'autocomplete-item';
          item.innerHTML = `
            <img src="${m.image}" class="autocomplete-img" alt="${m.title}">
            <div class="autocomplete-info">
              <h4>${m.title}</h4>
              <p>${m.priceText}</p>
            </div>
          `;
          autocompleteBox.appendChild(item);
        });
      } else {
        autocompleteBox.style.display = 'none';
      }
    });

    document.addEventListener('click', (e) => {
      if (!e.target.closest('.search-wrapper')) {
        autocompleteBox.style.display = 'none';
      }
    });
  }

  // Modal Logic — JS pixel-exact centering (immune to CSS stacking context bugs)
  const positionModal = () => {
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const padding = 16;
    const maxW = 800;
    const mw = Math.min(vw - padding * 2, maxW);
    const maxH = vh * 0.85;

    modal.style.position  = 'fixed';
    modal.style.width     = mw + 'px';
    modal.style.maxHeight = maxH + 'px';
    modal.style.left      = Math.round((vw - mw) / 2) + 'px';
    modal.style.top       = Math.round((vh - Math.min(modal.scrollHeight, maxH)) / 2) + 'px';
    modal.style.transform = 'none';
    modal.style.margin    = '0';
  };

  const openModal = (product) => {
    try {
      modalTitle.textContent = product.title;
      modalGrid.innerHTML = '';
      
      product.subProducts.forEach(sub => {
        const card = document.createElement('a');
        card.href = '#';
        card.className = 'premium-card';
        card.innerHTML = createCardHTML(sub);
        card.addEventListener('click', (e) => {
          e.preventDefault();
          window.location.href = `/${sub.slug}`;
        });
        modalGrid.appendChild(card);
      });

      // Show overlay first so modal has dimensions
      modalOverlay.classList.add('open');
      modal.style.display = 'flex';

      // Position after browser has rendered the content
      requestAnimationFrame(() => {
        positionModal();
        modal.style.opacity = '1';
      });

      document.body.style.overflow = 'hidden';
    } catch (err) {
      console.error('openModal error:', err);
    }
  };

  const closeModal = () => {
    modalOverlay.classList.remove('open');
    modal.style.opacity = '0';
    setTimeout(() => {
      modal.style.display = 'none';
      // Reset inline styles for next open
      modal.style.cssText = '';
    }, 300);
    document.body.style.overflow = '';
  };

  // Reposition on resize
  window.addEventListener('resize', () => {
    if (modal.style.display === 'flex') positionModal();
  });

  if(closeModalBtn) closeModalBtn.addEventListener('click', closeModal);
  if(modalOverlay) modalOverlay.addEventListener('click', (e) => {
    if (e.target === modalOverlay) closeModal();
  });
  
  // End of premium-data.js
});
