const reviewsDatabase = [
  {
    "id": 1,
    "category": "Streaming",
    "name": "Lucas N.",
    "avatarText": "L",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Muy buena opción para no pagar tanto mes a mes por ver series.",
    "verified": true
  },
  {
    "id": 2,
    "category": "Streaming",
    "name": "Lucía R.",
    "avatarText": "L",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Ayer",
    "text": "Buen servicio, tardó unos minutos pero ya estoy disfrutando del catálogo completo.",
    "verified": true
  },
  {
    "id": 3,
    "category": "Streaming",
    "name": "Tomás F.",
    "avatarText": "T",
    "avatarColor": "#ec4899",
    "rating": 4,
    "date": "Ayer",
    "text": "Llevo meses con la cuenta y nunca se me cayó. Pude terminar mi serie favorita sin interrupciones.",
    "verified": true
  },
  {
    "id": 4,
    "category": "Streaming",
    "name": "Valentina D.",
    "avatarText": "V",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Buen servicio, tardó unos minutos pero ya estoy disfrutando del catálogo completo.",
    "verified": true
  },
  {
    "id": 5,
    "category": "Streaming",
    "name": "Joaquín G.",
    "avatarText": "J",
    "avatarColor": "#14b8a6",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "Todo perfecto, me llegó rapidísimo el acceso y el catálogo de series está completo.",
    "verified": true
  },
  {
    "id": 6,
    "category": "Streaming",
    "name": "Sebastián M.",
    "avatarText": "S",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Buen servicio, tardó unos minutos pero ya estoy disfrutando del catálogo completo.",
    "verified": true
  },
  {
    "id": 7,
    "category": "Streaming",
    "name": "Santiago M.",
    "avatarText": "S",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo perfecto, me llegó rapidísimo el acceso y el catálogo de series está completo.",
    "verified": true
  },
  {
    "id": 8,
    "category": "Streaming",
    "name": "Lucía R.",
    "avatarText": "L",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo perfecto, me llegó rapidísimo el acceso y el catálogo de series está completo.",
    "verified": true
  },
  {
    "id": 9,
    "category": "Streaming",
    "name": "Micaela B.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Excelente servicio para ver series el fin de semana. Funciona bárbaro en la tele.",
    "verified": true
  },
  {
    "id": 10,
    "category": "Streaming",
    "name": "Florencia C.",
    "avatarText": "F",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Llevo meses con la cuenta y nunca se me cayó. Pude terminar mi serie favorita sin interrupciones.",
    "verified": true
  },
  {
    "id": 11,
    "category": "Streaming",
    "name": "Valentina G.",
    "avatarText": "V",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Excelente servicio para ver series el fin de semana. Funciona bárbaro en la tele.",
    "verified": true
  },
  {
    "id": 12,
    "category": "Streaming",
    "name": "Nicolás L.",
    "avatarText": "N",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Buen servicio, tardó unos minutos pero ya estoy disfrutando del catálogo completo.",
    "verified": true
  },
  {
    "id": 13,
    "category": "Streaming",
    "name": "Santiago G.",
    "avatarText": "S",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Muy buena opción para no pagar tanto mes a mes por ver series.",
    "verified": true
  },
  {
    "id": 14,
    "category": "Streaming",
    "name": "Diego R.",
    "avatarText": "D",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Excelente servicio para ver series el fin de semana. Funciona bárbaro en la tele.",
    "verified": true
  },
  {
    "id": 15,
    "category": "Streaming",
    "name": "Sofía L.",
    "avatarText": "S",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Excelente servicio para ver series el fin de semana. Funciona bárbaro en la tele.",
    "verified": true
  },
  {
    "id": 16,
    "category": "Streaming",
    "name": "Micaela S.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Todo perfecto, me llegó rapidísimo el acceso y el catálogo de series está completo.",
    "verified": true
  },
  {
    "id": 17,
    "category": "Streaming",
    "name": "Joaquín L.",
    "avatarText": "J",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Ayer",
    "text": "Todo perfecto, me llegó rapidísimo el acceso y el catálogo de series está completo.",
    "verified": true
  },
  {
    "id": 18,
    "category": "Streaming",
    "name": "Federico V.",
    "avatarText": "F",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "La cuenta anda impecable, lo compartí con mi familia y anduvo perfecto en la TV.",
    "verified": true
  },
  {
    "id": 19,
    "category": "Streaming",
    "name": "Lola J.",
    "avatarText": "L",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "La cuenta anda impecable, lo compartí con mi familia y anduvo perfecto en la TV.",
    "verified": true
  },
  {
    "id": 20,
    "category": "Streaming",
    "name": "Santiago N.",
    "avatarText": "S",
    "avatarColor": "#ec4899",
    "rating": 4,
    "date": "Ayer",
    "text": "Muy buena opción para no pagar tanto mes a mes por ver series.",
    "verified": true
  },
  {
    "id": 21,
    "category": "Gaming",
    "name": "Facundo H.",
    "avatarText": "F",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Excelente cuenta, pude entrar a jugar sin problemas. El soporte me ayudó con la instalación.",
    "verified": true
  },
  {
    "id": 22,
    "category": "Gaming",
    "name": "Florencia M.",
    "avatarText": "F",
    "avatarColor": "#ef4444",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "Totalmente recomendado para gamers. Me ahorré mucha plata comprando por acá.",
    "verified": true
  },
  {
    "id": 23,
    "category": "Gaming",
    "name": "Sebastián S.",
    "avatarText": "S",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Ayer",
    "text": "Rapidísimo. Pagué y al instante ya estaba jugando online con mis amigos.",
    "verified": true
  },
  {
    "id": 24,
    "category": "Gaming",
    "name": "Ignacio D.",
    "avatarText": "I",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Un lujo, pude instalar todo rapidísimo. Jugar así da gusto.",
    "verified": true
  },
  {
    "id": 25,
    "category": "Gaming",
    "name": "Julieta C.",
    "avatarText": "J",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Totalmente recomendado para gamers. Me ahorré mucha plata comprando por acá.",
    "verified": true
  },
  {
    "id": 26,
    "category": "Gaming",
    "name": "Renata J.",
    "avatarText": "R",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Ayer",
    "text": "La cuenta es Full Access real. Le cambié los datos y ya estoy viciando.",
    "verified": true
  },
  {
    "id": 27,
    "category": "Gaming",
    "name": "Mateo J.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Totalmente recomendado para gamers. Me ahorré mucha plata comprando por acá.",
    "verified": true
  },
  {
    "id": 28,
    "category": "Gaming",
    "name": "Paula B.",
    "avatarText": "P",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Un lujo, pude instalar todo rapidísimo. Jugar así da gusto.",
    "verified": true
  },
  {
    "id": 29,
    "category": "Gaming",
    "name": "Valentina J.",
    "avatarText": "V",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Excelente cuenta, pude entrar a jugar sin problemas. El soporte me ayudó con la instalación.",
    "verified": true
  },
  {
    "id": 30,
    "category": "Gaming",
    "name": "Facundo M.",
    "avatarText": "F",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Un lujo, pude instalar todo rapidísimo. Jugar así da gusto.",
    "verified": true
  },
  {
    "id": 31,
    "category": "Gaming",
    "name": "Facundo R.",
    "avatarText": "F",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Un lujo, pude instalar todo rapidísimo. Jugar así da gusto.",
    "verified": true
  },
  {
    "id": 32,
    "category": "Gaming",
    "name": "Lucas B.",
    "avatarText": "L",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "El acceso llegó al instante y funciona perfecto en los servidores premium. Cero lag.",
    "verified": true
  },
  {
    "id": 33,
    "category": "Gaming",
    "name": "Lola G.",
    "avatarText": "L",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Ayer",
    "text": "El acceso llegó al instante y funciona perfecto en los servidores premium. Cero lag.",
    "verified": true
  },
  {
    "id": 34,
    "category": "Gaming",
    "name": "Camila L.",
    "avatarText": "C",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hoy",
    "text": "El cheat funciona a la perfección, totalmente indetectable si lo usas bien. Gracias chicos.",
    "verified": true
  },
  {
    "id": 35,
    "category": "Gaming",
    "name": "Camila M.",
    "avatarText": "C",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "El acceso llegó al instante y funciona perfecto en los servidores premium. Cero lag.",
    "verified": true
  },
  {
    "id": 36,
    "category": "Gaming",
    "name": "Martina D.",
    "avatarText": "M",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "Es la tercera vez que les compro un juego y nunca decepcionan. Todo legal y funcional.",
    "verified": true
  },
  {
    "id": 37,
    "category": "Gaming",
    "name": "Lucas C.",
    "avatarText": "L",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Un lujo, pude instalar todo rapidísimo. Jugar así da gusto.",
    "verified": true
  },
  {
    "id": 38,
    "category": "Gaming",
    "name": "Bautista G.",
    "avatarText": "B",
    "avatarColor": "#8b5cf6",
    "rating": 4,
    "date": "Hoy",
    "text": "El cheat funciona a la perfección, totalmente indetectable si lo usas bien. Gracias chicos.",
    "verified": true
  },
  {
    "id": 39,
    "category": "Gaming",
    "name": "Tomás L.",
    "avatarText": "T",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hoy",
    "text": "Un lujo, pude instalar todo rapidísimo. Jugar así da gusto.",
    "verified": true
  },
  {
    "id": 40,
    "category": "Gaming",
    "name": "Sebastián M.",
    "avatarText": "S",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo perfecto, la cuenta me llegó rápido. Tuve un problema para instalar pero el soporte me lo resolvió.",
    "verified": true
  },
  {
    "id": 41,
    "category": "Music",
    "name": "Diego V.",
    "avatarText": "D",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo bien, me sumaron al plan familiar en segundos y ya estoy disfrutando.",
    "verified": true
  },
  {
    "id": 42,
    "category": "Music",
    "name": "Diego H.",
    "avatarText": "D",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Excelente calidad de audio. El plan premium se activó en mi propia cuenta en minutos.",
    "verified": true
  },
  {
    "id": 43,
    "category": "Music",
    "name": "Sebastián J.",
    "avatarText": "S",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero ya tengo mi música premium.",
    "verified": true
  },
  {
    "id": 44,
    "category": "Music",
    "name": "Mateo P.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero ya tengo mi música premium.",
    "verified": true
  },
  {
    "id": 45,
    "category": "Music",
    "name": "Agustín F.",
    "avatarText": "A",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Excelente calidad de audio. El plan premium se activó en mi propia cuenta en minutos.",
    "verified": true
  },
  {
    "id": 46,
    "category": "Music",
    "name": "Federico P.",
    "avatarText": "F",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Muy buena atención. La suscripción musical me salvó los viajes en tren.",
    "verified": true
  },
  {
    "id": 47,
    "category": "Music",
    "name": "Nicolás P.",
    "avatarText": "N",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Funciona bárbaro. Lo mejor de todo es poder descargar las canciones para cuando no hay wifi.",
    "verified": true
  },
  {
    "id": 48,
    "category": "Music",
    "name": "Gonzalo L.",
    "avatarText": "G",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Ayer",
    "text": "Escucho música sin interrupciones, la cuenta duró todos los meses pactados. 10/10.",
    "verified": true
  },
  {
    "id": 49,
    "category": "Music",
    "name": "Gonzalo G.",
    "avatarText": "G",
    "avatarColor": "#ec4899",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "Muy confiables, renové mis meses de música y todo salió perfecto como siempre.",
    "verified": true
  },
  {
    "id": 50,
    "category": "Music",
    "name": "Agustín L.",
    "avatarText": "A",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Escucho música sin interrupciones, la cuenta duró todos los meses pactados. 10/10.",
    "verified": true
  },
  {
    "id": 51,
    "category": "Music",
    "name": "Martina V.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Todo bien, me sumaron al plan familiar en segundos y ya estoy disfrutando.",
    "verified": true
  },
  {
    "id": 52,
    "category": "Music",
    "name": "Lucía F.",
    "avatarText": "L",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Ayer",
    "text": "Todo bien, me sumaron al plan familiar en segundos y ya estoy disfrutando.",
    "verified": true
  },
  {
    "id": 53,
    "category": "Music",
    "name": "Agustín D.",
    "avatarText": "A",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Ayer",
    "text": "Rapidísimo. Mandé el comprobante y ya estaba escuchando sin publicidad.",
    "verified": true
  },
  {
    "id": 54,
    "category": "Music",
    "name": "Joaquín N.",
    "avatarText": "J",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Funciona bárbaro. Lo mejor de todo es poder descargar las canciones para cuando no hay wifi.",
    "verified": true
  },
  {
    "id": 55,
    "category": "Music",
    "name": "Juan N.",
    "avatarText": "J",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo bien, me sumaron al plan familiar en segundos y ya estoy disfrutando.",
    "verified": true
  },
  {
    "id": 56,
    "category": "Music",
    "name": "Florencia N.",
    "avatarText": "F",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Excelente calidad de audio. El plan premium se activó en mi propia cuenta en minutos.",
    "verified": true
  },
  {
    "id": 57,
    "category": "Music",
    "name": "Lucas J.",
    "avatarText": "L",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Muy confiables, renové mis meses de música y todo salió perfecto como siempre.",
    "verified": true
  },
  {
    "id": 58,
    "category": "Music",
    "name": "Santiago D.",
    "avatarText": "S",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buena atención. La suscripción musical me salvó los viajes en tren.",
    "verified": true
  },
  {
    "id": 59,
    "category": "Music",
    "name": "Juan S.",
    "avatarText": "J",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Rapidísimo. Mandé el comprobante y ya estaba escuchando sin publicidad.",
    "verified": true
  },
  {
    "id": 60,
    "category": "Music",
    "name": "Agustín R.",
    "avatarText": "A",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Funciona bárbaro. Lo mejor de todo es poder descargar las canciones para cuando no hay wifi.",
    "verified": true
  },
  {
    "id": 61,
    "category": "AI Tools",
    "name": "Delfina N.",
    "avatarText": "D",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "El soporte me explicó re bien cómo acceder. Funciona de diez para mis proyectos.",
    "verified": true
  },
  {
    "id": 62,
    "category": "AI Tools",
    "name": "Lucía N.",
    "avatarText": "L",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buena herramienta. El acceso compartido es estable y siempre está disponible.",
    "verified": true
  },
  {
    "id": 63,
    "category": "AI Tools",
    "name": "Camila A.",
    "avatarText": "C",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Funciona bien, a veces la plataforma de IA está colapsada pero la cuenta siempre anda.",
    "verified": true
  },
  {
    "id": 64,
    "category": "AI Tools",
    "name": "Victoria N.",
    "avatarText": "V",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Poder usar el modelo avanzado me ahorró muchísimas horas de trabajo en código. Excelente.",
    "verified": true
  },
  {
    "id": 65,
    "category": "AI Tools",
    "name": "Valentina J.",
    "avatarText": "V",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buena herramienta. El acceso compartido es estable y siempre está disponible.",
    "verified": true
  },
  {
    "id": 66,
    "category": "AI Tools",
    "name": "Diego C.",
    "avatarText": "D",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Compré el acceso por 30 días y no se cortó ni una vez. Muy estable.",
    "verified": true
  },
  {
    "id": 67,
    "category": "AI Tools",
    "name": "Renata G.",
    "avatarText": "R",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hoy",
    "text": "El soporte me explicó re bien cómo acceder. Funciona de diez para mis proyectos.",
    "verified": true
  },
  {
    "id": 68,
    "category": "AI Tools",
    "name": "Sofía S.",
    "avatarText": "S",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "La IA responde rapidísimo y sin límites. Lo mejor que probé para la facultad.",
    "verified": true
  },
  {
    "id": 69,
    "category": "AI Tools",
    "name": "Lucía H.",
    "avatarText": "L",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Ayer",
    "text": "El soporte me explicó re bien cómo acceder. Funciona de diez para mis proyectos.",
    "verified": true
  },
  {
    "id": 70,
    "category": "AI Tools",
    "name": "Mateo G.",
    "avatarText": "M",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Un lujo, el acceso fue automático. Ahora trabajo mil veces más rápido.",
    "verified": true
  },
  {
    "id": 71,
    "category": "AI Tools",
    "name": "Nicolás J.",
    "avatarText": "N",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Muy buena herramienta. El acceso compartido es estable y siempre está disponible.",
    "verified": true
  },
  {
    "id": 72,
    "category": "AI Tools",
    "name": "Gonzalo B.",
    "avatarText": "G",
    "avatarColor": "#2563eb",
    "rating": 4,
    "date": "Hace 1 semana",
    "text": "Excelente opción para usar IA de pago sin gastar una fortuna. Totalmente recomendado.",
    "verified": true
  },
  {
    "id": 73,
    "category": "AI Tools",
    "name": "Renata F.",
    "avatarText": "R",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Un lujo, el acceso fue automático. Ahora trabajo mil veces más rápido.",
    "verified": true
  },
  {
    "id": 74,
    "category": "AI Tools",
    "name": "Matías P.",
    "avatarText": "M",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "La IA responde rapidísimo y sin límites. Lo mejor que probé para la facultad.",
    "verified": true
  },
  {
    "id": 75,
    "category": "AI Tools",
    "name": "Santiago A.",
    "avatarText": "S",
    "avatarColor": "#8b5cf6",
    "rating": 4,
    "date": "Hoy",
    "text": "Me ayuda muchísimo con mis tareas, el acceso a las funciones plus vuela.",
    "verified": true
  },
  {
    "id": 76,
    "category": "AI Tools",
    "name": "Federico V.",
    "avatarText": "F",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Ayer",
    "text": "Poder usar el modelo avanzado me ahorró muchísimas horas de trabajo en código. Excelente.",
    "verified": true
  },
  {
    "id": 77,
    "category": "AI Tools",
    "name": "Agustín T.",
    "avatarText": "A",
    "avatarColor": "#14b8a6",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "Compré el acceso por 30 días y no se cortó ni una vez. Muy estable.",
    "verified": true
  },
  {
    "id": 78,
    "category": "AI Tools",
    "name": "Renata M.",
    "avatarText": "R",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Funciona bien, a veces la plataforma de IA está colapsada pero la cuenta siempre anda.",
    "verified": true
  },
  {
    "id": 79,
    "category": "AI Tools",
    "name": "Agustín B.",
    "avatarText": "A",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Ayer",
    "text": "Me ayuda muchísimo con mis tareas, el acceso a las funciones plus vuela.",
    "verified": true
  },
  {
    "id": 80,
    "category": "AI Tools",
    "name": "Ignacio T.",
    "avatarText": "I",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Muy buena herramienta. El acceso compartido es estable y siempre está disponible.",
    "verified": true
  },
  {
    "id": 81,
    "category": "Discord",
    "name": "Ignacio S.",
    "avatarText": "I",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Rapidísimo, en menos de 5 minutos ya tenía los emojis y el banner animado.",
    "verified": true
  },
  {
    "id": 82,
    "category": "Discord",
    "name": "Bautista L.",
    "avatarText": "B",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Ayer",
    "text": "Increíble la rapidez. Mandé mensaje por Instagram y mi server ya estaba full.",
    "verified": true
  },
  {
    "id": 83,
    "category": "Discord",
    "name": "Santiago J.",
    "avatarText": "S",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Ayer",
    "text": "Todo perfecto, me llegó el código rápido. Tuve una duda y el soporte me ayudó al instante.",
    "verified": true
  },
  {
    "id": 84,
    "category": "Discord",
    "name": "Nicolás A.",
    "avatarText": "N",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen precio para el Nitro, lo vengo renovando hace meses por acá.",
    "verified": true
  },
  {
    "id": 85,
    "category": "Discord",
    "name": "Mateo D.",
    "avatarText": "M",
    "avatarColor": "#ec4899",
    "rating": 4,
    "date": "Hace 2 días",
    "text": "Increíble la rapidez. Mandé mensaje por Instagram y mi server ya estaba full.",
    "verified": true
  },
  {
    "id": 86,
    "category": "Discord",
    "name": "Agustín L.",
    "avatarText": "A",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Ayer",
    "text": "Excelente servicio de boost para mi server. Subió de nivel enseguida.",
    "verified": true
  },
  {
    "id": 87,
    "category": "Discord",
    "name": "Matías J.",
    "avatarText": "M",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Increíble la rapidez. Mandé mensaje por Instagram y mi server ya estaba full.",
    "verified": true
  },
  {
    "id": 88,
    "category": "Discord",
    "name": "Ignacio N.",
    "avatarText": "I",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Todo perfecto, me llegó el código rápido. Tuve una duda y el soporte me ayudó al instante.",
    "verified": true
  },
  {
    "id": 89,
    "category": "Discord",
    "name": "Sofía G.",
    "avatarText": "S",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Rapidísimo, en menos de 5 minutos ya tenía los emojis y el banner animado.",
    "verified": true
  },
  {
    "id": 90,
    "category": "Discord",
    "name": "Matías S.",
    "avatarText": "M",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Todo perfecto, me llegó el código rápido. Tuve una duda y el soporte me ayudó al instante.",
    "verified": true
  },
  {
    "id": 91,
    "category": "Discord",
    "name": "Lucía R.",
    "avatarText": "L",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Increíble la rapidez. Mandé mensaje por Instagram y mi server ya estaba full.",
    "verified": true
  },
  {
    "id": 92,
    "category": "Discord",
    "name": "Facundo S.",
    "avatarText": "F",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Compré keys de miembros y funcionaron bárbaro, las fui usando de a poco.",
    "verified": true
  },
  {
    "id": 93,
    "category": "Discord",
    "name": "Lucía B.",
    "avatarText": "L",
    "avatarColor": "#2563eb",
    "rating": 4,
    "date": "Hace 1 semana",
    "text": "Todo perfecto, me llegó el código rápido. Tuve una duda y el soporte me ayudó al instante.",
    "verified": true
  },
  {
    "id": 94,
    "category": "Discord",
    "name": "Matías L.",
    "avatarText": "M",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo legal y funcional. Los miembros del servidor se ven muy reales.",
    "verified": true
  },
  {
    "id": 95,
    "category": "Discord",
    "name": "Bautista L.",
    "avatarText": "B",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen precio para el Nitro, lo vengo renovando hace meses por acá.",
    "verified": true
  },
  {
    "id": 96,
    "category": "Discord",
    "name": "Delfina T.",
    "avatarText": "D",
    "avatarColor": "#ef4444",
    "rating": 4,
    "date": "Hoy",
    "text": "Rapidísimo, en menos de 5 minutos ya tenía los emojis y el banner animado.",
    "verified": true
  },
  {
    "id": 97,
    "category": "Discord",
    "name": "Milagros L.",
    "avatarText": "M",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Rapidísimo, en menos de 5 minutos ya tenía los emojis y el banner animado.",
    "verified": true
  },
  {
    "id": 98,
    "category": "Discord",
    "name": "Ignacio C.",
    "avatarText": "I",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo legal y funcional. Los miembros del servidor se ven muy reales.",
    "verified": true
  },
  {
    "id": 99,
    "category": "Discord",
    "name": "Diego T.",
    "avatarText": "D",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Excelente servicio de boost para mi server. Subió de nivel enseguida.",
    "verified": true
  },
  {
    "id": 100,
    "category": "Discord",
    "name": "Julieta L.",
    "avatarText": "J",
    "avatarColor": "#ef4444",
    "rating": 4,
    "date": "Hoy",
    "text": "El Nitro se activó al instante con el promo link. Muchas gracias!",
    "verified": true
  },
  {
    "id": 101,
    "category": "Creator Tools",
    "name": "Victoria R.",
    "avatarText": "V",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Ayer",
    "text": "Pude exportar todos mis diseños sin marca de agua y con las herramientas premium. Excelente.",
    "verified": true
  },
  {
    "id": 102,
    "category": "Creator Tools",
    "name": "Renata R.",
    "avatarText": "R",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hoy",
    "text": "Un lujo poder editar videos sin restricciones. El programa funciona 10 puntos.",
    "verified": true
  },
  {
    "id": 103,
    "category": "Creator Tools",
    "name": "Milagros D.",
    "avatarText": "M",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Lo mejor que probé para creadores de contenido. Muy estable y económico.",
    "verified": true
  },
  {
    "id": 104,
    "category": "Creator Tools",
    "name": "Sebastián B.",
    "avatarText": "S",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Me sumaron al equipo pro en mi cuenta personal súper rápido. Muy confiables.",
    "verified": true
  },
  {
    "id": 105,
    "category": "Creator Tools",
    "name": "Milagros M.",
    "avatarText": "M",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hoy",
    "text": "Pude exportar todos mis diseños sin marca de agua y con las herramientas premium. Excelente.",
    "verified": true
  },
  {
    "id": 106,
    "category": "Creator Tools",
    "name": "Paula L.",
    "avatarText": "P",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Ayer",
    "text": "Buen servicio, tardó unos minutitos el mail pero ya estoy en el equipo pro.",
    "verified": true
  },
  {
    "id": 107,
    "category": "Creator Tools",
    "name": "Micaela L.",
    "avatarText": "M",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Un lujo poder editar videos sin restricciones. El programa funciona 10 puntos.",
    "verified": true
  },
  {
    "id": 108,
    "category": "Creator Tools",
    "name": "Ignacio H.",
    "avatarText": "I",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Increíble. Hice el pedido y en minutos ya estaba armando mis flyers en máxima calidad.",
    "verified": true
  },
  {
    "id": 109,
    "category": "Creator Tools",
    "name": "Gonzalo N.",
    "avatarText": "G",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Ayer",
    "text": "Lo mejor que probé para creadores de contenido. Muy estable y económico.",
    "verified": true
  },
  {
    "id": 110,
    "category": "Creator Tools",
    "name": "Florencia H.",
    "avatarText": "F",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Un lujo poder editar videos sin restricciones. El programa funciona 10 puntos.",
    "verified": true
  },
  {
    "id": 111,
    "category": "Creator Tools",
    "name": "Micaela B.",
    "avatarText": "M",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "La invitación me llegó al correo en segundos. Empecé a usar las plantillas premium enseguida.",
    "verified": true
  },
  {
    "id": 112,
    "category": "Creator Tools",
    "name": "Sofía N.",
    "avatarText": "S",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo de diez, uso la cuenta todos los días para editar y cero problemas.",
    "verified": true
  },
  {
    "id": 113,
    "category": "Creator Tools",
    "name": "Lucas G.",
    "avatarText": "L",
    "avatarColor": "#a322ff",
    "rating": 4,
    "date": "Ayer",
    "text": "La invitación me llegó al correo en segundos. Empecé a usar las plantillas premium enseguida.",
    "verified": true
  },
  {
    "id": 114,
    "category": "Creator Tools",
    "name": "Milagros H.",
    "avatarText": "M",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Ayer",
    "text": "Buen servicio, tardó unos minutitos el mail pero ya estoy en el equipo pro.",
    "verified": true
  },
  {
    "id": 115,
    "category": "Creator Tools",
    "name": "Paula A.",
    "avatarText": "P",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "Increíble. Hice el pedido y en minutos ya estaba armando mis flyers en máxima calidad.",
    "verified": true
  },
  {
    "id": 116,
    "category": "Creator Tools",
    "name": "Diego L.",
    "avatarText": "D",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo de diez, uso la cuenta todos los días para editar y cero problemas.",
    "verified": true
  },
  {
    "id": 117,
    "category": "Creator Tools",
    "name": "Micaela C.",
    "avatarText": "M",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Todo de diez, uso la cuenta todos los días para editar y cero problemas.",
    "verified": true
  },
  {
    "id": 118,
    "category": "Creator Tools",
    "name": "Mateo R.",
    "avatarText": "M",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hoy",
    "text": "Lo mejor que probé para creadores de contenido. Muy estable y económico.",
    "verified": true
  },
  {
    "id": 119,
    "category": "Creator Tools",
    "name": "Diego S.",
    "avatarText": "D",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hoy",
    "text": "Me sumaron al equipo pro en mi cuenta personal súper rápido. Muy confiables.",
    "verified": true
  },
  {
    "id": 120,
    "category": "Creator Tools",
    "name": "Santiago V.",
    "avatarText": "S",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo de diez, uso la cuenta todos los días para editar y cero problemas.",
    "verified": true
  },
  {
    "id": 121,
    "category": "Sports Streaming",
    "name": "Paula T.",
    "avatarText": "P",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Ayer",
    "text": "Cero delay en las transmisiones. La cuenta funciona perfecto.",
    "verified": true
  },
  {
    "id": 122,
    "category": "Sports Streaming",
    "name": "Micaela M.",
    "avatarText": "M",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "El pase deportivo anduvo bárbaro para toda la fecha. Recomendadísimo.",
    "verified": true
  },
  {
    "id": 123,
    "category": "Sports Streaming",
    "name": "Renata S.",
    "avatarText": "R",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Cero delay en las transmisiones. La cuenta funciona perfecto.",
    "verified": true
  },
  {
    "id": 124,
    "category": "Sports Streaming",
    "name": "Joaquín J.",
    "avatarText": "J",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "El pase deportivo anduvo bárbaro para toda la fecha. Recomendadísimo.",
    "verified": true
  },
  {
    "id": 125,
    "category": "Sports Streaming",
    "name": "Agustín T.",
    "avatarText": "A",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Ayer",
    "text": "Rapidísimo. Pagué y al toque ya estaba gritando los goles.",
    "verified": true
  },
  {
    "id": 126,
    "category": "Sports Streaming",
    "name": "Florencia V.",
    "avatarText": "F",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Por el precio, es la mejor forma de ver fútbol y automovilismo el finde.",
    "verified": true
  },
  {
    "id": 127,
    "category": "Sports Streaming",
    "name": "Martina S.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Ayer",
    "text": "La cuenta Lifetime es un golazo. Ya vi varios eventos y nunca un problema.",
    "verified": true
  },
  {
    "id": 128,
    "category": "Sports Streaming",
    "name": "Victoria D.",
    "avatarText": "V",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hoy",
    "text": "Funciona bien, tuve una pequeña desconexión pero reconecté y anduvo el resto de la carrera.",
    "verified": true
  },
  {
    "id": 129,
    "category": "Sports Streaming",
    "name": "Paula T.",
    "avatarText": "P",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo perfecto, me llegó justo antes del clásico y lo pude ver de diez.",
    "verified": true
  },
  {
    "id": 130,
    "category": "Sports Streaming",
    "name": "Joaquín R.",
    "avatarText": "J",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Excelente servicio para los que seguimos todos los deportes. Muy estable.",
    "verified": true
  },
  {
    "id": 131,
    "category": "Sports Streaming",
    "name": "Matías J.",
    "avatarText": "M",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Ayer",
    "text": "Rapidísimo. Pagué y al toque ya estaba gritando los goles.",
    "verified": true
  },
  {
    "id": 132,
    "category": "Sports Streaming",
    "name": "Matías H.",
    "avatarText": "M",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy confiables. Responden rápido si tenés drama justo antes de un partido.",
    "verified": true
  },
  {
    "id": 133,
    "category": "Sports Streaming",
    "name": "Milagros H.",
    "avatarText": "M",
    "avatarColor": "#f97316",
    "rating": 4,
    "date": "Hoy",
    "text": "La cuenta Lifetime es un golazo. Ya vi varios eventos y nunca un problema.",
    "verified": true
  },
  {
    "id": 134,
    "category": "Sports Streaming",
    "name": "Mateo A.",
    "avatarText": "M",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Funciona bien, tuve una pequeña desconexión pero reconecté y anduvo el resto de la carrera.",
    "verified": true
  },
  {
    "id": 135,
    "category": "Sports Streaming",
    "name": "Nicolás P.",
    "avatarText": "N",
    "avatarColor": "#ec4899",
    "rating": 4,
    "date": "Hace 3 días",
    "text": "El pase deportivo anduvo bárbaro para toda la fecha. Recomendadísimo.",
    "verified": true
  },
  {
    "id": 136,
    "category": "Sports Streaming",
    "name": "Micaela V.",
    "avatarText": "M",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Ayer",
    "text": "El pase deportivo anduvo bárbaro para toda la fecha. Recomendadísimo.",
    "verified": true
  },
  {
    "id": 137,
    "category": "Sports Streaming",
    "name": "Micaela J.",
    "avatarText": "M",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "El pase deportivo anduvo bárbaro para toda la fecha. Recomendadísimo.",
    "verified": true
  },
  {
    "id": 138,
    "category": "Sports Streaming",
    "name": "Victoria A.",
    "avatarText": "V",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy confiables. Responden rápido si tenés drama justo antes de un partido.",
    "verified": true
  },
  {
    "id": 139,
    "category": "Sports Streaming",
    "name": "Sebastián A.",
    "avatarText": "S",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo perfecto, me llegó justo antes del clásico y lo pude ver de diez.",
    "verified": true
  },
  {
    "id": 140,
    "category": "Sports Streaming",
    "name": "Sebastián V.",
    "avatarText": "S",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo perfecto, me llegó justo antes del clásico y lo pude ver de diez.",
    "verified": true
  },
  {
    "id": 141,
    "category": "Software & Learning",
    "name": "Diego N.",
    "avatarText": "D",
    "avatarColor": "#10b981",
    "rating": 4,
    "date": "Hoy",
    "text": "Los códigos de activación funcionaron a la primera. Todo muy legal y rápido.",
    "verified": true
  },
  {
    "id": 142,
    "category": "Software & Learning",
    "name": "Lucía A.",
    "avatarText": "L",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Ya no me quedo sin vidas aprendiendo idiomas. La cuenta se vinculó enseguida.",
    "verified": true
  },
  {
    "id": 143,
    "category": "Software & Learning",
    "name": "Renata M.",
    "avatarText": "R",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo bien, me dieron soporte por una duda con la activación y lo solucionaron rápido.",
    "verified": true
  },
  {
    "id": 144,
    "category": "Software & Learning",
    "name": "Valentina R.",
    "avatarText": "V",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Me activaron el plan anual en mi perfil en minutos. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 145,
    "category": "Software & Learning",
    "name": "Facundo T.",
    "avatarText": "F",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Aprender sin anuncios te cambia la vida. Recomendado al 100%.",
    "verified": true
  },
  {
    "id": 146,
    "category": "Software & Learning",
    "name": "Renata N.",
    "avatarText": "R",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Ayer",
    "text": "Excelente opción para tener licencias originales sin pagar locuras.",
    "verified": true
  },
  {
    "id": 147,
    "category": "Software & Learning",
    "name": "Valentina S.",
    "avatarText": "V",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hoy",
    "text": "Me activaron el plan anual en mi perfil en minutos. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 148,
    "category": "Software & Learning",
    "name": "Bautista F.",
    "avatarText": "B",
    "avatarColor": "#ec4899",
    "rating": 4,
    "date": "Hace 2 días",
    "text": "Todo bien, me dieron soporte por una duda con la activación y lo solucionaron rápido.",
    "verified": true
  },
  {
    "id": 149,
    "category": "Software & Learning",
    "name": "Nicolás M.",
    "avatarText": "N",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Me activaron el plan anual en mi perfil en minutos. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 150,
    "category": "Software & Learning",
    "name": "Paula S.",
    "avatarText": "P",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Ayer",
    "text": "Excelente opción para tener licencias originales sin pagar locuras.",
    "verified": true
  },
  {
    "id": 151,
    "category": "Software & Learning",
    "name": "Victoria L.",
    "avatarText": "V",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hoy",
    "text": "Excelente opción para tener licencias originales sin pagar locuras.",
    "verified": true
  },
  {
    "id": 152,
    "category": "Software & Learning",
    "name": "Renata J.",
    "avatarText": "R",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Ayer",
    "text": "Todo de diez. Pude hacer mis cursos sin límites y la plataforma vuela.",
    "verified": true
  },
  {
    "id": 153,
    "category": "Software & Learning",
    "name": "Lucía B.",
    "avatarText": "L",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hoy",
    "text": "Me activaron el plan anual en mi perfil en minutos. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 154,
    "category": "Software & Learning",
    "name": "Lucía N.",
    "avatarText": "L",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Ayer",
    "text": "Todo bien, me dieron soporte por una duda con la activación y lo solucionaron rápido.",
    "verified": true
  },
  {
    "id": 155,
    "category": "Software & Learning",
    "name": "Bautista B.",
    "avatarText": "B",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "El soporte me guió paso a paso para canjear el código. Unos genios.",
    "verified": true
  },
  {
    "id": 156,
    "category": "Software & Learning",
    "name": "Florencia V.",
    "avatarText": "F",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hoy",
    "text": "Excelente opción para tener licencias originales sin pagar locuras.",
    "verified": true
  },
  {
    "id": 157,
    "category": "Software & Learning",
    "name": "Bautista B.",
    "avatarText": "B",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Aprender sin anuncios te cambia la vida. Recomendado al 100%.",
    "verified": true
  },
  {
    "id": 158,
    "category": "Software & Learning",
    "name": "Sebastián N.",
    "avatarText": "S",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo bien, me dieron soporte por una duda con la activación y lo solucionaron rápido.",
    "verified": true
  },
  {
    "id": 159,
    "category": "Software & Learning",
    "name": "Bautista B.",
    "avatarText": "B",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Aprender sin anuncios te cambia la vida. Recomendado al 100%.",
    "verified": true
  },
  {
    "id": 160,
    "category": "Software & Learning",
    "name": "Tomás V.",
    "avatarText": "T",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Excelente opción para tener licencias originales sin pagar locuras.",
    "verified": true
  },
  {
    "id": 161,
    "category": "VPN & Security",
    "name": "Diego A.",
    "avatarText": "D",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Me llegó el usuario al instante. Pude desbloquear el contenido que quería ver.",
    "verified": true
  },
  {
    "id": 162,
    "category": "VPN & Security",
    "name": "Juan S.",
    "avatarText": "J",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "La cuenta premium anda de diez, pude configurar la VPN en la tele incluso.",
    "verified": true
  },
  {
    "id": 163,
    "category": "VPN & Security",
    "name": "Bautista N.",
    "avatarText": "B",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo perfecto. Te ahorras mucha plata y tenés la mejor seguridad.",
    "verified": true
  },
  {
    "id": 164,
    "category": "VPN & Security",
    "name": "Florencia G.",
    "avatarText": "F",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Excelente VPN, la conexión es súper estable y no me baja los megas.",
    "verified": true
  },
  {
    "id": 165,
    "category": "VPN & Security",
    "name": "Joaquín G.",
    "avatarText": "J",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Buen servicio, tardó un poquito en conectar el primer servidor pero después anduvo genial.",
    "verified": true
  },
  {
    "id": 166,
    "category": "VPN & Security",
    "name": "Milagros L.",
    "avatarText": "M",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen servicio. Ideal para jugar con bajo ping en servidores de afuera.",
    "verified": true
  },
  {
    "id": 167,
    "category": "VPN & Security",
    "name": "Matías V.",
    "avatarText": "M",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Todo perfecto. Te ahorras mucha plata y tenés la mejor seguridad.",
    "verified": true
  },
  {
    "id": 168,
    "category": "VPN & Security",
    "name": "Sofía P.",
    "avatarText": "S",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Un lujo, la velocidad es inmejorable. Nada que envidiar a pagar precio completo.",
    "verified": true
  },
  {
    "id": 169,
    "category": "VPN & Security",
    "name": "Lucas J.",
    "avatarText": "L",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Ayer",
    "text": "Protección total a un precio increíble. La app funciona bárbaro en PC y celu.",
    "verified": true
  },
  {
    "id": 170,
    "category": "VPN & Security",
    "name": "Julieta J.",
    "avatarText": "J",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Buen servicio, tardó un poquito en conectar el primer servidor pero después anduvo genial.",
    "verified": true
  },
  {
    "id": 171,
    "category": "VPN & Security",
    "name": "Agustín R.",
    "avatarText": "A",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Ayer",
    "text": "Me llegó el usuario al instante. Pude desbloquear el contenido que quería ver.",
    "verified": true
  },
  {
    "id": 172,
    "category": "VPN & Security",
    "name": "Tomás H.",
    "avatarText": "T",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Cero cortes navegando todo el día. Muy buena opción para estar seguro.",
    "verified": true
  },
  {
    "id": 173,
    "category": "VPN & Security",
    "name": "Sofía R.",
    "avatarText": "S",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Buen servicio, tardó un poquito en conectar el primer servidor pero después anduvo genial.",
    "verified": true
  },
  {
    "id": 174,
    "category": "VPN & Security",
    "name": "Lucía L.",
    "avatarText": "L",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Todo perfecto. Te ahorras mucha plata y tenés la mejor seguridad.",
    "verified": true
  },
  {
    "id": 175,
    "category": "VPN & Security",
    "name": "Gonzalo A.",
    "avatarText": "G",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Cero cortes navegando todo el día. Muy buena opción para estar seguro.",
    "verified": true
  },
  {
    "id": 176,
    "category": "VPN & Security",
    "name": "Sebastián R.",
    "avatarText": "S",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Ayer",
    "text": "Excelente VPN, la conexión es súper estable y no me baja los megas.",
    "verified": true
  },
  {
    "id": 177,
    "category": "VPN & Security",
    "name": "Lucas J.",
    "avatarText": "L",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Excelente VPN, la conexión es súper estable y no me baja los megas.",
    "verified": true
  },
  {
    "id": 178,
    "category": "VPN & Security",
    "name": "Julieta J.",
    "avatarText": "J",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hoy",
    "text": "Protección total a un precio increíble. La app funciona bárbaro en PC y celu.",
    "verified": true
  },
  {
    "id": 179,
    "category": "VPN & Security",
    "name": "Nicolás D.",
    "avatarText": "N",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Excelente VPN, la conexión es súper estable y no me baja los megas.",
    "verified": true
  },
  {
    "id": 180,
    "category": "VPN & Security",
    "name": "Delfina V.",
    "avatarText": "D",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Ayer",
    "text": "Buen servicio, tardó un poquito en conectar el primer servidor pero después anduvo genial.",
    "verified": true
  },
  {
    "id": 181,
    "category": "Social Boost",
    "name": "Lucas P.",
    "avatarText": "L",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Las visualizaciones subieron mis estadísticas un montón. Totalmente recomendado.",
    "verified": true
  },
  {
    "id": 182,
    "category": "Social Boost",
    "name": "Facundo A.",
    "avatarText": "F",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo perfecto, tuve una duda con el link y el soporte me contestó al toque.",
    "verified": true
  },
  {
    "id": 183,
    "category": "Social Boost",
    "name": "Florencia G.",
    "avatarText": "F",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Increíble cómo me levantó el alcance. Súper satisfecho con la compra.",
    "verified": true
  },
  {
    "id": 184,
    "category": "Social Boost",
    "name": "Juan P.",
    "avatarText": "J",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Los likes entraron al instante en mi post. Súper confiable y económico.",
    "verified": true
  },
  {
    "id": 185,
    "category": "Social Boost",
    "name": "Camila H.",
    "avatarText": "C",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Los seguidores llegaron súper rápido y no se cayeron. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 186,
    "category": "Social Boost",
    "name": "Milagros J.",
    "avatarText": "M",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Ayer",
    "text": "Compré para varios reels y en todos funcionó bárbaro. Cero drama.",
    "verified": true
  },
  {
    "id": 187,
    "category": "Social Boost",
    "name": "Lucía G.",
    "avatarText": "L",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "Los likes entraron al instante en mi post. Súper confiable y económico.",
    "verified": true
  },
  {
    "id": 188,
    "category": "Social Boost",
    "name": "Joaquín S.",
    "avatarText": "J",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Las visualizaciones subieron mis estadísticas un montón. Totalmente recomendado.",
    "verified": true
  },
  {
    "id": 189,
    "category": "Social Boost",
    "name": "Sebastián S.",
    "avatarText": "S",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Ayer",
    "text": "Espectacular para darle un empujón a la cuenta. Todo de primera.",
    "verified": true
  },
  {
    "id": 190,
    "category": "Social Boost",
    "name": "Joaquín D.",
    "avatarText": "J",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Buen servicio, tardó unos minutitos en empezar pero después subió todo rapidísimo.",
    "verified": true
  },
  {
    "id": 191,
    "category": "Social Boost",
    "name": "Ignacio A.",
    "avatarText": "I",
    "avatarColor": "#a322ff",
    "rating": 4,
    "date": "Ayer",
    "text": "Espectacular para darle un empujón a la cuenta. Todo de primera.",
    "verified": true
  },
  {
    "id": 192,
    "category": "Social Boost",
    "name": "Gonzalo N.",
    "avatarText": "G",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Los seguidores llegaron súper rápido y no se cayeron. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 193,
    "category": "Social Boost",
    "name": "Federico J.",
    "avatarText": "F",
    "avatarColor": "#10b981",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "Las visualizaciones subieron mis estadísticas un montón. Totalmente recomendado.",
    "verified": true
  },
  {
    "id": 194,
    "category": "Social Boost",
    "name": "Renata T.",
    "avatarText": "R",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Los seguidores llegaron súper rápido y no se cayeron. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 195,
    "category": "Social Boost",
    "name": "Lucas N.",
    "avatarText": "L",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Los seguidores llegaron súper rápido y no se cayeron. Muy buen servicio.",
    "verified": true
  },
  {
    "id": 196,
    "category": "Social Boost",
    "name": "Joaquín F.",
    "avatarText": "J",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "Las visualizaciones subieron mis estadísticas un montón. Totalmente recomendado.",
    "verified": true
  },
  {
    "id": 197,
    "category": "Social Boost",
    "name": "Sebastián T.",
    "avatarText": "S",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Todo perfecto, tuve una duda con el link y el soporte me contestó al toque.",
    "verified": true
  },
  {
    "id": 198,
    "category": "Social Boost",
    "name": "Tomás L.",
    "avatarText": "T",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Rapidísimo. Pagué y en menos de media hora ya tenía todo lo que pedí.",
    "verified": true
  },
  {
    "id": 199,
    "category": "Social Boost",
    "name": "Renata C.",
    "avatarText": "R",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Las visualizaciones subieron mis estadísticas un montón. Totalmente recomendado.",
    "verified": true
  },
  {
    "id": 200,
    "category": "Social Boost",
    "name": "Federico R.",
    "avatarText": "F",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hoy",
    "text": "Rapidísimo. Pagué y en menos de media hora ya tenía todo lo que pedí.",
    "verified": true
  },
  {
    "id": 201,
    "category": "General",
    "name": "Julieta D.",
    "avatarText": "J",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Rapidísimo. Pagas, mandas el comprobante y te lo activan en el momento. Muy confiables, no duden en comprar.",
    "verified": true
  },
  {
    "id": 202,
    "category": "General",
    "name": "Julieta M.",
    "avatarText": "J",
    "avatarColor": "#f97316",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 203,
    "category": "General",
    "name": "Nicolás V.",
    "avatarText": "N",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 204,
    "category": "General",
    "name": "Camila M.",
    "avatarText": "C",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 205,
    "category": "General",
    "name": "Florencia G.",
    "avatarText": "F",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Rapidísimo. Pagas, mandas el comprobante y te lo activan en el momento. Muy confiables, no duden en comprar.",
    "verified": true
  },
  {
    "id": 206,
    "category": "General",
    "name": "Mateo B.",
    "avatarText": "M",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 207,
    "category": "General",
    "name": "Facundo C.",
    "avatarText": "F",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 208,
    "category": "General",
    "name": "Camila F.",
    "avatarText": "C",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Rapidísimo. Pagas, mandas el comprobante y te lo activan en el momento. Muy confiables, no duden en comprar.",
    "verified": true
  },
  {
    "id": 209,
    "category": "General",
    "name": "Agustín T.",
    "avatarText": "A",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo perfecto, me llegó rapidísimo. Tuve un pequeño problema pero el soporte me lo resolvió al instante.",
    "verified": true
  },
  {
    "id": 210,
    "category": "General",
    "name": "Matías L.",
    "avatarText": "M",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Rapidísimo. Pagas, mandas el comprobante y te lo activan en el momento. Muy confiables, no duden en comprar.",
    "verified": true
  },
  {
    "id": 211,
    "category": "General",
    "name": "Ignacio G.",
    "avatarText": "I",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 212,
    "category": "General",
    "name": "Camila B.",
    "avatarText": "C",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Todo legal y transparente. Un placer comprar en esta tienda.",
    "verified": true
  },
  {
    "id": 213,
    "category": "General",
    "name": "Paula P.",
    "avatarText": "P",
    "avatarColor": "#ef4444",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Compro siempre por acá y nunca me fallan. Totalmente recomendado para cualquier servicio.",
    "verified": true
  },
  {
    "id": 214,
    "category": "General",
    "name": "Florencia T.",
    "avatarText": "F",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 215,
    "category": "General",
    "name": "Mateo M.",
    "avatarText": "M",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo legal y transparente. Un placer comprar en esta tienda.",
    "verified": true
  },
  {
    "id": 216,
    "category": "General",
    "name": "Ignacio S.",
    "avatarText": "I",
    "avatarColor": "#2563eb",
    "rating": 4,
    "date": "Hace 3 días",
    "text": "Me sorprendió la rapidez de entrega, es literal al instante. Lo mejor que probé.",
    "verified": true
  },
  {
    "id": 217,
    "category": "General",
    "name": "Juan H.",
    "avatarText": "J",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 218,
    "category": "General",
    "name": "Joaquín D.",
    "avatarText": "J",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 219,
    "category": "General",
    "name": "Lola S.",
    "avatarText": "L",
    "avatarColor": "#14b8a6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Un lujo, funciona 10 puntos. Y la atención al cliente es lo más.",
    "verified": true
  },
  {
    "id": 220,
    "category": "General",
    "name": "Delfina R.",
    "avatarText": "D",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo legal y transparente. Un placer comprar en esta tienda.",
    "verified": true
  },
  {
    "id": 221,
    "category": "General",
    "name": "Renata M.",
    "avatarText": "R",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Compro siempre por acá y nunca me fallan. Totalmente recomendado para cualquier servicio.",
    "verified": true
  },
  {
    "id": 222,
    "category": "General",
    "name": "Delfina G.",
    "avatarText": "D",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo perfecto, me llegó rapidísimo. Tuve un pequeño problema pero el soporte me lo resolvió al instante.",
    "verified": true
  },
  {
    "id": 223,
    "category": "General",
    "name": "Camila M.",
    "avatarText": "C",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Un lujo, funciona 10 puntos. Y la atención al cliente es lo más.",
    "verified": true
  },
  {
    "id": 224,
    "category": "General",
    "name": "Matías C.",
    "avatarText": "M",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Ayer",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 225,
    "category": "General",
    "name": "Juan S.",
    "avatarText": "J",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 226,
    "category": "General",
    "name": "Santiago A.",
    "avatarText": "S",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo legal y transparente. Un placer comprar en esta tienda.",
    "verified": true
  },
  {
    "id": 227,
    "category": "General",
    "name": "Lola H.",
    "avatarText": "L",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Ayer",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 228,
    "category": "General",
    "name": "Gonzalo G.",
    "avatarText": "G",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Todo legal y transparente. Un placer comprar en esta tienda.",
    "verified": true
  },
  {
    "id": 229,
    "category": "General",
    "name": "Martina C.",
    "avatarText": "M",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 230,
    "category": "General",
    "name": "Gonzalo P.",
    "avatarText": "G",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Todo perfecto, me llegó rapidísimo. Tuve un pequeño problema pero el soporte me lo resolvió al instante.",
    "verified": true
  },
  {
    "id": 231,
    "category": "General",
    "name": "Julieta H.",
    "avatarText": "J",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Un lujo, funciona 10 puntos. Y la atención al cliente es lo más.",
    "verified": true
  },
  {
    "id": 232,
    "category": "General",
    "name": "Facundo C.",
    "avatarText": "F",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "Todo perfecto, me llegó rapidísimo. Tuve un pequeño problema pero el soporte me lo resolvió al instante.",
    "verified": true
  },
  {
    "id": 233,
    "category": "General",
    "name": "Matías R.",
    "avatarText": "M",
    "avatarColor": "#a322ff",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 234,
    "category": "General",
    "name": "Gonzalo R.",
    "avatarText": "G",
    "avatarColor": "#f59e0b",
    "rating": 4,
    "date": "Hace unas horas",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 235,
    "category": "General",
    "name": "Facundo L.",
    "avatarText": "F",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Me sorprendió la rapidez de entrega, es literal al instante. Lo mejor que probé.",
    "verified": true
  },
  {
    "id": 236,
    "category": "General",
    "name": "Micaela C.",
    "avatarText": "M",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "Compro siempre por acá y nunca me fallan. Totalmente recomendado para cualquier servicio.",
    "verified": true
  },
  {
    "id": 237,
    "category": "General",
    "name": "Federico B.",
    "avatarText": "F",
    "avatarColor": "#8b5cf6",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 238,
    "category": "General",
    "name": "Sofía D.",
    "avatarText": "S",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hoy",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 239,
    "category": "General",
    "name": "Gonzalo J.",
    "avatarText": "G",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 3 días",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 240,
    "category": "General",
    "name": "Juan R.",
    "avatarText": "J",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 241,
    "category": "General",
    "name": "Micaela B.",
    "avatarText": "M",
    "avatarColor": "#f59e0b",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Excelente servicio. Es la tercera vez que les compro y nunca decepcionan. Los precios son inmejorables.",
    "verified": true
  },
  {
    "id": 242,
    "category": "General",
    "name": "Delfina P.",
    "avatarText": "D",
    "avatarColor": "#10b981",
    "rating": 5,
    "date": "Hace unas horas",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 243,
    "category": "General",
    "name": "Victoria N.",
    "avatarText": "V",
    "avatarColor": "#f97316",
    "rating": 4,
    "date": "Hace 2 días",
    "text": "Excelente servicio. Es la tercera vez que les compro y nunca decepcionan. Los precios son inmejorables.",
    "verified": true
  },
  {
    "id": 244,
    "category": "General",
    "name": "Tomás M.",
    "avatarText": "T",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hoy",
    "text": "Me sorprendió la rapidez de entrega, es literal al instante. Lo mejor que probé.",
    "verified": true
  },
  {
    "id": 245,
    "category": "General",
    "name": "Joaquín N.",
    "avatarText": "J",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hoy",
    "text": "Buen servicio, tardó unos minutos más de lo esperado pero el producto funciona perfecto.",
    "verified": true
  },
  {
    "id": 246,
    "category": "General",
    "name": "Valentina T.",
    "avatarText": "V",
    "avatarColor": "#a322ff",
    "rating": 5,
    "date": "Hace 1 semana",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 247,
    "category": "General",
    "name": "Joaquín P.",
    "avatarText": "J",
    "avatarColor": "#2563eb",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "Excelente servicio. Es la tercera vez que les compro y nunca decepcionan. Los precios son inmejorables.",
    "verified": true
  },
  {
    "id": 248,
    "category": "General",
    "name": "Ignacio P.",
    "avatarText": "I",
    "avatarColor": "#f97316",
    "rating": 5,
    "date": "Hace 2 días",
    "text": "La atención por mensaje directo es super rápida y amable. 10/10.",
    "verified": true
  },
  {
    "id": 249,
    "category": "General",
    "name": "Joaquín P.",
    "avatarText": "J",
    "avatarColor": "#ec4899",
    "rating": 5,
    "date": "Ayer",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  },
  {
    "id": 250,
    "category": "General",
    "name": "Victoria R.",
    "avatarText": "V",
    "avatarColor": "#a322ff",
    "rating": 4,
    "date": "Hace 1 semana",
    "text": "Muy buen servicio y soporte. Responden enseguida ante cualquier duda.",
    "verified": true
  }
];